---
title: "2-Trofico"
author: "VNV"
date: "2024-03-25"
output: html_document
editor_options: 
  markdown: 
    wrap: 90
---

# Ecología trófica del sistema detritívoro del suelo

En el suelo se encuentra aproximadamente la mitad de la biomasa total de animales que
habitan la Tierra, la mayor diversidad de estos animales se relaciona con la hojarasca y
con el suelo en el cual contribuyen con diversas funciones del ecosistema relacionadas con
la descomposición del material orgánico que se acumula sobre el suelo, son piezas claves
en los servicios ecosistemicos tales como el ciclo de los nutrientes, por lo tanto se
correlacionan con la fertilidad de los suelos y su productividad en términos económicos,
el ciclo del carbono, por lo que se vinculan con el cambio climático a gran escala, forman
parte de los factores formadores del suelo a través de sus actividades a microescala (o
dicho de otro modo a nivel local o puntual) por lo que contribuyen al ciclo hídrico y a la
fertilidad física del suelo y la red trófica y el entramado de interacciones entre los
miembros de la comunidad se relacionan estrechamente con el control de poblaciones que
pueden resultar críticas para la actividad agrícola entendiendo que una comunidad edáfica
podría ser incapaz de regular poblaciones de patógenos si la red trófica que esta conforma
no regula al patógeno. (\@.citas)

En esta sección resumimos las carácterísticas de la ecología trófica de los principales
taxones de animales del suelo vinculados con el sistema detritívoro encargado de
descomponer la materia orgánica, principalmente hojarasca, que se acumula sobre el suelo o
proveniente de las raices muertas dentro del suelo mineral. La diversidad de taxones
implica una diversidad de recursos alimenticios utiliados por cada uno de ellos. La
revisión se basa en los libros de Dindal, Soil Biology Burges, Atlas de soil Eisenbeis y
Wichard que corresponden a la bibliografía clásica sobre este aspecto y que basa su
desarrollo en la evidencia empírica de la época , es decir observaciones directas del
comportamiento alimenticio en mesocosmos y microcosmos, ensayos de alimentación, análisis
de contenido intestinal, observación de las partes anatómicas bucales y Feeding habits de
Potapov2022 en la que los autores expertos en diferentes taxones utilizan las herramientas
actuales, tales como isótopos estables, análisis de ácidos grasos, y análisis del ADN a
nivel del contenido intestinal para dilucidar los hábitos alimenticios de estos animales
reforzando la evidencia empírica anterior y a la vez relacionandolos con diversos aspectos
como la especialización en hábitats, rasgos individuales como el tamaño corporal entre
otros.

# Microfauna

## Eukariota: Protozoa

Los protozoos de vida libre se encuentran normalmente asociados con las capas
superficiales del suelo y se caracterian por su intima relacion con el tejido vegetal en
descomposición.

Estos organismos son los principales predadores de las bacterias del suelo por lo que
influyen tanto en la regulación como en la caracerización de las comunidades de bacterias
del suelo. Por otra parte el papel de los diferentes taxones que pueden componer la
comunidad de protozoos del suelo sobre la comunidad de bacterias no varía sino más bien en
el grado en el que las afectan.

Como mecanismos de nutrición los protozoos pueden ser fagotróficos, en el que enguyen el
alimento, u osmotrópicos, mecanismo mediante el cual los nutrientes pasan del medio
extracelular hacia el interior celular.

Además solo algunas especies son consumidores de materia orgánica en un estado avanzado de
descomposición "humus" de manera facultativa cuando las poblaciones bacterianas que foman
parte de su dieta son escasas, los prozoos también predan sobre otros protozoos y sobre
levaduras e hifas de hongos.

Los protozoos intervienen en el ciclo de la materia orgánica de manera indirecta mediante
la predación continua sobre las bacterias y otra microflora, a su vez, estos son presas de
otros organismos, intervinene también en el ciclo de nutrientes mediante la liberación de
compuestos asimilables por las raices de los vegetales. La fauna protozoaria del suelo es
cosmopolita y varia ampliamente segun las condiciones puntuales al nivel de sus
microhábitats "la zona de bio films" o las condiciones ambientales relacionadas con el
hábitat edáfico.

## Ecdysozoa: Tardigrada

Lor tardigrados son micrometazoos que se encuentran en hábitats marinos, acuáticos y
terrestres, el largo corporal de aquellos que habitan los suelos en promedio varía entre
las 200 y 700 $\mu$m, su coloración general es pálidad blancuzca pero pueden tomar
diferentes colores.

Los tardígrados terrestres requieren de una película de agua para permanecer activos y
desarrollar sus actividades, además de habitar la hojarasca y los primeros centímetros del
suelo pueden encontrarse asociados a musgos, líquenes y helechos.
<!-- tardigrados abigarrados color "violeta", en suelos de unlu"-->

El mecanismo de alimentación de los tardígrados involucra el uso del estilete bucal para
perforar el alimento y succionar el contenido del mismo, los tardígrados de gran tamaño
son predadores y capturan protozoos, nemátodos y otros tardígrados, los tardígrados de
menor tamaño consumen material vegetal descompuesto, bacterias y hongos y también los hay
aquellos que son herbívoros que consumen plantas no vasculares.

## Ecdysozoa: Nematoda

Los nemátodos son animales con un gran capacidad para ocupar una amplia diversidad de
hábitats que contengan una película de agua, son gusanos cilíndricos y elongados con
simetria bilateral y no segmentados.

Los nemátodos de vida libre del suelo son los metazoos más abundantes varían en su tamaño
pero en general son de un largo menor a 7 mm, su caracterización anatomo-morfológica está
desarrollada y permite la clasificación taxonómica de estos hasta el nivel de genero
(\@.chaves_etal2019).

Los nemátodos poseen una serie de adaptaciones a diferentes hábitos alimenticios que se
observa mediante la diversidad de sus sistemas digestivos específicamente adaptaciones
morfológicas bien aparentes en la región anterior del tracto digestivo, estos animales
mediante el mecanismo de succión permiten el ingreso del alimento a travéz de la apertura
bucal además poseen la capacidad de perforar células y de desgarrar a su presa según el
mecanismo de alimentación del nemátodo en cuestión.

Estas adaptaciones se correlacionan con su modo principal de alimentación y por lo que las
partes bucales permiten definir grupos tróficos y cuya clasificación es corroborada por la
evidencia empírica más reciente.

Los grupo tróficos de nemátodos de vida libre del suelo son: los nemátodos bacteríofagos,
los nemátodos fungívoros, ambos se encuentran vinculados funcionalmente con la regulación
poblacional de las comunidades de la microflora, los nemátodos predadores que predan sobre
protozoos, tardígrados, y otros nemátodos, los nemátodos omnívoros, estos regulan las
poblaciones de la microfauna y son importantes en el control de poblaciones fitófagas y
los nemátodos fitófagos que parasitan las raices y tejidos vegetales y que resultan de
interés productivo por su potencial efecto nocivo sobre especies de interés agronómico
(\@.momoyfalco2009, \@.yeatesetal1993).

# Mesofauna

## Oligochaeta: Enchytraeidae

Los enquitreidos es una familia de Oligochaetes que se encuentran en habitat terrestres,
litorales y acuáticos. Son gusanos segmentados cuyo largo no supera los 15 mm y en general
su cuerpo es de color pálido blancuzco. Estos animales se relacionan con la formación del
suelo debida a su papel en la fragmentación de la materia orgánica, su mezcla con la
fracción mineral del suelo y la deposición de capsulas fecales ("pellets fecales") sobre
el suelo a medida que van abriendo canales a través del suelo (\@.O'CONNOR1968). Dash
(1990) comenta que los enquitreidos consumen remanentes vegetales, sílice, grandes
cantidades de hifas de hongos, algas unicelulares, bacterias y nemátodos fitófagos. Además
los enquitreidos muestran preferencia por los hongos y por material vegetal en
descomposición con una gran cantidad de hifas de hongos además consumen las heces de los
colémbolos junto con la hojarasca fragmentada.

## Myriapoda: Pauropoda

Los paurópodos son pequeños miriápodos blanquecinos y ciegos su cuerpo cilíndrico y unos
pocos pares de patas aproximadamente entre 8 y 11 alcanzando largos de hasta 1,5 mm.
Habitan principalmente en los poros del suelo mineral y orgánico (\@.raw1967), entre la
hojarasca, entre los troncos en descomposición y lugares donde permanece oscuro, la
humedad alta y temperaturas moderadas. Su movilidad es reducida, sus partes bucales son
poco desarrolladas y consumen hifas de hongos principalmente y fluidos que son producto
del material vegetal descompuesto (\@.scheller1990).

## Myriapoda: Symphyla

La clase sínfila habitan los suelos alrededor del mundo son importante en el
fraccionamiento de la materia orgánica del cual obtienen sus nutrientes y además se
alimentan de pequeñas raices y raicillas. Son animáles elongados, blanquecinos, con hasta
12 pares de patas y pueden alcanzar largos de hasta 1,5 cm, debido a su forma corporal
pueden recorrer a lo largo de los poros del suelo orgánico mineral (\@.edwards1990).
Edwards 1990 menciona como hábitos alimenticios que la clase incluye especie voraces
consumiendo hasta 20 veces su peso, algunos son herbívoros pudiendo llegar a causar daños
en especies vegetales de interés productivo, pero en general se alimentan de material
vegetal en descomposición, microrganimos, nemátodos y carroña de invertebrados.

## Hexapoda: Protura

Los proturos son hexapodos diminutos, delgados, aplanados, ciegos, se encuentran en la
hojarasca y el suelo orgánico, debajo de troncos y piedras en lugares donde se mantienen
la humedad alta entre los poros e intersticios que ellos ocupan y también se hallan a
profundidades mayores a los 5 cm en el suelo mineral (\@.copeland_imadaté1990). Sobre los
items alimenticios de estos animales poco se conoce, sus piezas bucales incuyen un
estilete que le permite alimentarse mediante succión, se sabe que se alimentan de las
hifas de hongos y específicamente ha sido documentada alimentandose sobre ectomicorrizas
(\@.potapov2018),

## Hexapoda: Diplura

Los dipluros son hexapodos alargados, de pequeño tamaño, adaptados a la vida en los poros
del suelo, su característica es el apéndice caudal que puede ser del tipo pinzas de fuerza
(Japygidos) o de tipo filamento (Campodeidos).

Ambas clases de animales son omnívoros con preferencia por items alimenticios animales que
incluyen colémbolos, ácaros, dipluros (i.e. canivales), sínfilos, larvas de insectos,
enquitreidos y en menor grado consumen detritos y micelios y esporas de hongos
(\@.ferguson1990).

## Arachnida: Acari y Hexapoda: Collembola

Los ácaros y colémbolos constituyen los miembros del sistema edáfico más abundante del
grupo de la mesofauna. Estos animales poseen una gran diversidad de hábitos tróficos que
incluyen: a) predadores que se alimentan de nemátodos, colémbolos, ácaros, otros
microartrópodos, larvas de invertebrados, enquitreidos, huevos de invertebrados; b)
detritívoros que consumen hojarasca y material vegetal en descomposición; c)
microfitófagos que incluye a organismos que consumen la microflora del suelo es decir
protistas y hongos; y los d) omnívoros. Esta diversidad de hábitos alimenticios varia
según la familia taxonómica considerada y será tratada en profundidad en la siguiente
sección.

# Macrofauna

## Oligochaeta: Crassiclitellata

(\@.satchell1967) La lombrices de tierra son gusanos pertenecen a los Oligochaeta y se
encuentran en una amplia variedad de ecosistemas terrestres con excepcion de lugares
áridos o zonas desérticas debido a sus requerimientos de humedad para poder llevar
adelante sus actividades (Schewert 1990). Son importantes en el funcionamiento del
ecosistema del suelo debido a su capacidad de cavar galerias a través del suelo mineral,
de mezclar la hojarasca con el suelo y con bacterias intestinales y de transportar y
relocalizar la materia orgánica que toma de la superficie y la deposita como heces blandas
("castings") en cuya composición se encuentran nutrientes asimilables por las plantas
(\@.momofalco2019; \@.schewert1990). Las lombrices se alimentan ya sea enguyendo el suelo,
enguyendo porciones de hojarasca y materia orgánica o una combinación de ambas, a su vez,
las especies pueden encontrarse viviendo entre los intersticios que se forma entre la
hojarasca y la superficie del suelo o pueden habitar en el suelo orgánico-mineral medio en
el cual se habren paso construyendo galerías. Por su mecanismo de alimentación son
saprófagas, alimentandose de la materia orgánica en descomposición aunque al mismo tiempo
consumen organismos de la microflora, de la microfauna, consumen humus y partículas de
suelo mineral.

## Arachnida: Araneae

Las arañas de la hojarasca habitan sobre la hojarasca que se acumula sobre el suelo y
entre los intersiticios y espacios que puedan formarse entre el suelo, la hojarasca,
troncos y rocas.

Son organismos solitarios en su gran mayoría e importantes depredadores (\@.dondale 1990)
tal es así que se ha cuantificado que a nivel global las arañas en todos los niveles
espaciales consumen entre 400 y 800 M de toneladas anuales en términos de biomasa de
presas. Como depredares poseen dos estrategias para capturar a sus presas, aquellas arañas
que buscan activamente a su presa y aquellas que se "sientan a esperar" hasta que la
presas caigan en sus trampas, una vez la presa ha sido capturada la inmovilizan y
predigieren el contenido interno a través de enzimas que inyectan mediante sus estructuras
bucales y finalmente succionan los fluidos corporales. Sus items alimenticios incluyen una
amplia variedad de artrópodos como dípteros, hymenópteros, coleópteros, hemípteros,
miríapodos, isópodos y colémbolos.

## Arachnida: Pseudoscorpionida

Los pseudoscorpiones son pequeños arácnidos similares a los escorpiones pero no poseen
como parte de su forma corporal una cola, que en caso de los escorpiones esta es larga y
curvada con un aguijón ponzoñoso al final. Son artrópodos predadores en el suelo cuyas
presas incluyen a los ácaros y colémbolos, trips, dipteros, otros pequeños artrópodos y
larvas de coleópteros, Muchmore (1990) comenta que la estrategia de caza es esperar a que
la presa pase y luego capturarla. De manera similar a las arañas, los psudoescoprpiones al
atrapar a la presa inyectan enzimas y se alimentan de sus fluidos. Debido a su pequeño
tamaño sus hábitos de vida son crípticos ocupando los pequeños espacios que se forman
entre la hojaras, el suelo, troncos,rocas, etc. y moviendose fácilmente a través de ellos
y hacia otros espacios sobre el suelo, tales como, los troncos de árboles, superficies de
grandes piedras, etc (\@.muchmore1990).

## Myriapoda: Chilopoda

Conocidos como cienpies (\@.mundel1990) son depredadores y según su adaptación corporal
buscan las presas sobre y entre la hojarasca, también a través de los poros del suelo
orgánico mineral o en los espacios que se forman entre piedras o troncos que se mantienen
húmedos y oscuros. Las estructuras anatómicas relacionadas con la región anterior permiten
procesar a la presa tienen formas de pinzas en la cual se encuentran los ductos de las
glándulas que liberan toxinas para matar a su presa. Su alimentación incluye a artrópodos
y otros invertebrados, como lombrices de tierra, colémbolos, ácaros, arañas, otros
cienpies, gasteropodos, etc.

## Myriapoda: Diplopoda

Conocidos como milpies son animales terrestres comunes de hallar al remover la hojarasca y
sobre el suelo orgánico y cuando son encontrados algunos se enrrollan sobre si mismos
formando una espiral, su cuerpo se encuentra protegido por su rígida estrutura y sumando a
esta característica algunos liberan sustancias repelentes para evitar o protegerse del
ataque de los predadores. Los diplópodos, que viven en los suelos, son detritívoros se
alimentan principalmente de hojarasca, además de materia orgánica en descomposición y
ocasionalmente de la carroña de invertebrados, para ello utilizan sus piezas bucales para
cortar el tejido vegetal, ingerirlo y dejan a su paso cápsulas fecales con la hojarasca
fragmentada y embebida con la microbiota (\@.hoffman1990).

## Isopoda: Oniscoidea

Conocidos comúnmente como "bichos bolita" estos animales son crustáceos terrestres cuya
morfología corporal les permite esconderse sobre sí mismos formando una "bolita" ante una
amenaza. Los oniscoideos son animales gregarios detritívoros que consumen hojarasca, hifas
de hongos, heces y carroña de invertebrados y en algunos casos plántulas, requieren de
humedad alta para llevar adelantes sus actividades, poseen estructuras rígidas y glándulas
repelentes que lo protegen de los predadores, son hallados entre la hojarasca, sobre la
superficie y en lugares donde permanezca húmedo y oscuro.

## Insecta: Blattodea

El orden de los insectos Blattodea incluye a los animales común mente conocidos como
cucarachas y a las termitas que serán tratados abajo. Estos animales poseen en su tracto
intestinal un microbiota especializada en la alimentación basada en celulosa y compuestos
recalcitrantes provenientes de la hojarasca y la madera en descomposición por lo que son
importantes detritívoros son hallados en lugares húmedos y oscuros como ser la hojarasca,
debajo de troncos y piedras.

## Insecta: Isoptera

Las termitas son insectos sociales cuya importancia en el suelo radica en su capacidad de
modificar la estrutura de este de manera puntual al construir su nidos. Sus modos
alimenticios incluyen la herbivoría mediante el consumo de tejido vegetal vivo tanto de
raices como de las estructura vegetales que se encuentra sobre el suelo y la detritivoría
en el cual utilizan materiales ricos en celulosa.

Nutting (1990) menciona que los isópteros consumen vegetación muerta tanto la hojarasca
como troncos y ramas en descomposición, bosta, hifas de hongos y humus.

Por otra parte, debido a su forma de alimentación y su forma de vida las termitas son
importantes agentes liberadores de metano y dióxido de carbono.

## Insecta: Psocoptera

Son insectos con un largo corporal de hasta 12mm, según su categoría ecológica los hay
quiene cumplen todo su ciclo de vida en la hojarasca y aquellos que son transitorios. Se
alimentan con preferencia de las hifas de hongos y de partículas de material orgánico en
avanzado estado de descomposición (detritos en ingles: "debris"), además se incluye
también el consumo de algas y líquenes.

## Coleóptera: Carabidae

Los carábidos pertenecen a una familia de coleópteros que habitan la superficie de los
suelos en el que se halla la hojarasca, tienen la capacidad de formar espacios a través
del suelo orgánico en el que se resguardan pero su efecto sobre la estructura del suelo es
puntual e ínfimo. Estos escarabajos son carnívoros y se alimentan de todo tipo de presas
que puedan capturar entre sus apéndices y también los hay aquellos que se alimentan de
presas enfermas convalecientes y de carroña de animales invertebrados, aunque también
existen especies hervívoras en la familia estas se hallan sobre el suelo, por otra parte
existen especialistas cuyas adaptaciones bucales le permiten consumir gastrópodos,
diplododos, colémbolos y microartrópodos, coleópteros estafilínidos y huevos de insectos.
Su mecanismo de alimentación es peculiar, utilizando la digestión extraoral, fragmentan a
sus presas, las enrollan y las almacenan un tiempo a manera de un cultivo que está
digiriendose. Con respecto a la alimentación de las larvas de los carábidos se asumen que
se alimentan de items similares a aquelos que consumen los adultos, algunas especies
poseen estructurs bucales que permiten capturar y perforar a los microartrópodos (Bell
1990).

## Coleoptera: Staphylinidae

Los escarabajos estafilinidos son una familia de coleópteros muy diversa y especiosa,
estos se caracterizan por su élitros cortos y truncados, el abdomen expuesto y con el
cuerpo elongado en la mayoría de los habitantes del suelo alcanzando largos de hasta 3,5
cm. Los estafilínidos son predaores ágiles en los hábitats que se encuentra entre la
hojarasca y los poros del suelo orgánico, sus presas incluyen a los colémbolos, ácaros,
ácaros oribátidos, larvas y adultos de escarabajos e insectos de pequeño tamaño y
nemátodos. Similar a los carábidos ellos hacen uso de la estrategia de digestión extra
oral de sus presas capturadas y procesadas. Las excepciones a este modo alimenticio
incluyen su alimentación sobre material orgánico descompuesto y hongos (\@.newton1960)

## Coleoptera: Ptiliidae

La familia de Ptiliidae incluye escarabajos más pequeños con largos de hasta 1mm. Habitan
en la hojarasca y sitios en el cual exista una alta humedad tal que permita el desarrollo
de hongos de los cuales se alimenta (\@.dybas1990) Los ptiliidae son predadores
(\@.raw1967).

## Coleoptera: Scarabaeidae

Las larvas de los escarabajos escarabeidos, conocidos como "gusano blanco", son el estadío
que habitan de los suelos en el cual se habren paso a través del suelo orgánico mineral
cavando túneles, son características de esta larva su gran tamaño, la posición que toman
naturalmente en forma de "C", la cabeza definida oscura y los espiráculos visibles a lo
largo de los laterales del cuerpo de la larva, poseen partes bucales bien definidas que le
permiten masticar el alimento. Algunas de estas larvas son reconocidas por su impacto
económico al alimentarse de las raices de plantas cultivada, pero en la mayoría de las
especies la alimentación de estas larvas se basa en el consumo de material vegetal en
descomposición, hojarasca y raices, humus, estiercol y carroña. Los adultos de esta
familia pueden ser coprófagos, carroñeros, herbívoros o no alimentarse (Tashiro 1990).

## Insecta: Diptera

El orden de los dípteros en el que se encuentran las moscas y mosquitos son importantes en
el suelo en su estadío larval, muchas especies de dipteros depositan sus huevos en el
material orgánico en descomosición o directamente sobre el suelo, en zonas donde la
humedad es alta y constante y la materia orgánica es abundante, posteriormente los huevos
eclosionan y sus larvas se alimentan de las hifas de hongos, hojarasca en descomosición,
suelo orgánico, humus, estiercol, carroña y en fluidos ricos en compuestos orgánicos
(\@.mcalpine1990; \@.teskey1990).

## Hymenoptera: Formicidae

Las hormigas son insectos sociales cuya actividad sobre el suelo es de importancia debida
a las moificaciones que hacen en el mismo para construir sus nidos y su impacto puede ser
sobre una superficie de unos pocos cm² hasta varios m². Son animales cuya alimentación
amplia sugiere clasificarlos como omnívoros ya que hacen uso de partes vegetales como de
partes animales para abastecer la demanda nutricional del hongo del cual se alimentan.

En el suelo los formícidos son principalente predadores generalistas capturando tanto a
presas más pequeñas, tales como colémbolos ácaros y demás microartrópodos, como a presas
de mayor tamaño al trabajar en equipo, donde se incluyen lombrices de tierra, caracoles,
miriápodos, arañas, larvas de invertebrados, termitas, coleópteros y otros insectos. Su
importancia es tal que (\@.potapovetal2022) menciona que las hormigas se encargan de
remover hasta el 60% de los artrópodos que se encuentran sobre los suelos de bosques
templados.

## Gastropoda terrestres.

Los moluscos terrestres son los caracoles y babosas estos prefieren hábitats húmedos, con
abundante cantidad de alimento y una fuente de calcio. Estos animales requieren de la
presencia de humedad constante y tanto adultos como huevos no resisten la desecación
extrema por lo que recurren a estrategias de evitación para tolerar condiciones de sequía.

Estos animales habitan entre la hojarasca y el suelo orgánico ("humus"). En general se
define a los gastrópodos como herbívoros generalistas, pero estos son aquellos que viven y
se alimentan en el sistema que se forma sobre el suelo, en el sistema detritívoro del
suelo ellos consumen hongos, bacterias, tejido vegetal senescente y humus por lo que son
considerados pricipalmente como microbívoros.

# Referencias

Chaves et al 2019 Clave para determinar generos de nematodos de la república argentina.

Burch y Pearce 1990 GASTROPODA in Dindal 1990

Dash 1990 Oligochaeta: Enchytraeidae in Dindal 1990

Schewert 1990 Oligochaeta: Enchytraeidae in Dindal 1990

Momo y Falco 2019 Biologia y Ecología de la fauna del suelo

Dondale 1990 Litter Araneae in Dindal 1990

Dondale 1990 Chilopoda in Dindal 1990

Dondale 1990 Diplopoda in Dindal 1990

Scheller 1990 Pauropoda in Dindal 1990

Edwards 1990 Pauropoda in Dindal 1990

Copeland and Imadaté 1990 Protura in Dindal 1990

Ferguson 1990 Diplura in Dindal 1990

Nutting 1990 Isoptera in Dindal 1990

Bell 1990 Carabidae in Dindal 1990 Bell 1990

Ptiliidae in Dindal 1990 Divas 1990 Ptiliidae in Dindal 1990

Tashiro 1990 Scarabaeidae larvae in Dindal 1990

McAlpine 1990 Diptera larvae in Dindal 1990

Teskey 1990 Diptera larvae larvae in Dindal 1990

O'connor The Enchytraeid, in Soil Biology de Burges y Raw 1967

Satchell 1967 Lumbrícidos, in Soil Biology de Burges y Raw 1967

Raw 1967 Artrópodos (excepto ácaros y colémbolos) in Soil Biology de Burges y Raw 1967

Potapov 2018 paper donde dice que ve a protura comer ectomicorriza
