---
title: "borrador"
author: "VNV"
date: "2024-02-09"
output: html_document
editor_options: 
  markdown: 
    wrap: 72
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Importancia de los organismos del suelo en el funcionamiento del ecosistema edáfico

El suelo es el componente principal de la biósfera terrestre (Georges P.
en (Lavelle and Spain 1994)) y el sustrato físico sobre el que se dan la
mayor parte de las actividades humanas (Brussaard 1997).

En la matriz del suelo interactuan de manera dinámica y estrecha los
diferentes componentes físicos, químicos y biológicos (@culliney2013,
Lavelle and Spain 1994; Wall et al. 2012). Estas interacciones afectan
la estructura y funcionamiento del suelo regulando el funcionamiento de
los ecosistemas terrestres tanto en ambientes naturales como en los
suelos manejados por el hombre (Barrios 2007; Brussaard 1997).

Los bienes y servicios que la humanidad aprovecha de los ecosistemas
terrestres dependen de los procesos naturales que ocurren en el suelo y
del efecto de las actividades humanas sobre el suelo (Barrios 2007; Wall
et al. 2012) que puedene modificar la estructura física y química del
suelo, producir cambios en la dinámica del ciclo de los nutrientes y la
materia orgánica, que influyen en la dinámica del almacenamiento del
carbono y del agua y en la liberación y captura de los gases de efecto
invernadero (Barrios 2007; Lavelle et al. 2006) que afectan el
funcionamiento del ecosistema del suelo.

Amplio es el conocimiento desarrollado sobre los componentes físicos y
químicos del suelo que permiten la clasificación y caracterización de
estos, pero sobre el componente biológico aún se está desarrollando el
cuerpo de conocimiento (Barrios 2007).

Es importante avanzar en el conocimiento del componente biológico del
suelo en el cuál habita una amplia diversidad de organismos
(@culliney2013 @lavelle_etal_2006) de los cuales dependen los diferentes
procesos que ocurren en el suelo y que se relacionan con el
funcionamiento del suelo @Thaku_etal_2019 debido a las interacciones
entre los organismos y el medio ambiente edáfico cuyos efectos a
diferentes escalas espaciales y temporales (@barrios2007
@lavelle_etal_2006) regulan los servicios ecosistémicos del suelo
(@bardgett2002 @creamer2022).

El suelo como hábitat proporciona una multiplicidad de nichos a través
de la red de poros e intersticios que se forman entre la matriz del
suelo (@lavelle_spain2003, @wall_etal2012) y la hojarasca que se acumula
sobre el suelo. La red de poros es un entorno anfibio, compacto,
discontinuo, de diámetro variable con características físicas y químicas
heterogéneas a pequeñas escalas en la que se desarrollan y mantienen una
gran cantidad de microclimas y soporta una compleja y diversa comunidad
biológica (@lavelle_spain2003 @barrios2007 @bardgett2002)

La diversidad de especies que habitan en los suelos se correlaciona
positivamente con la heterogeneidad de hábitats que se forman entre la
hojarasca y el suelo a la vez los organismos que habitan los
intersticios del suelo, mediante diferentes estrategias de alimentación
e historias de vida, evitan la competencia interespecífica y responden
diferencialmente a las variaciones ambientales y a la disponibilidad de
recursos tróficos alimenticios (@bardgett2002, @lavelle_spain2003). El
estudio de la riqueza de especies se dificulta porque el suelo es un
hábitat críptico, porque el tamaño de los organismos es pequeño, lo que
dificulta las caracterizaciones anotomicas - morfológicas, y por el bajo
desarrollo a nivel global del conocimiento taxonómico
(@wurts_et_al2012). Por otra parte, considerando los diferentes procesos
que ocurren en el suelo, muchas especies cumplen papeles similares por
lo que una clasificación funcional es necesaria para conectar la
diversidad con el funcionamiento del ecosistema (@briones2014,
@lavelle_etal_2006).

El enfoque que permite integrar la diversidad de especies, las
interacciones interespecíficas, las interacciones con el ambiente, la
redundancia funcional, el papel de las especies claves y la
multiplicidad de canales de materia y energia que ocurren en los
ecosistemas es estudio de la red de interacciones (@barrios2007,
@briones2014, @potapov2023) que permite simplificar la complejidad de
interacciones y conetarlos con diferentes parámetros que emergen el
estudio de los ecosistemas (@Hooperetal2005;@delmas_etal2019)

Los organismos que viven en el suelo tradicionalmente son clasificados
según el ancho corporal: los organismos \<100 $\mu m$ incluyen la
microbiota (bacterias y hongos), organismos \<200 $\mu m$ se denominan
microfauna (protozoa, nematoda, etc.), siguen a estos la mesofauna con
anchos coporales \< 2mm (microartrópodos y enquitreidos) y la macrofauna
que son aquellos animales con un ancho corporal mayor a los 2 mm, estos
incluyen artrópodos, lombrices de tierra y otros invertebrados
(@briones2014,@lavelle_spain2003) y algunos autores incluyen la
megafauna aquellos animales con un ancho corporal mayor a 2 cm
(@wurst_etal_2012). Los organismos según su rango de tamaño se adaptan a
la vida en el suelo mediante diferentes estrategias en sus fomas de vida
y fisiología (@lavelle2012), en los poros e intersticios del suelo
existen diferentes regímenes hídricos, de cantidad de aire y de espacio
en la heterogeneidad de ambientes en el habitan los organismos con
diferentes restricciones en la movilidad, diferentes grados de
especialización trófica (@potapov2023) y en el cual se han desarrollado
mutualismos (@lavelle2012,@lavelle2006) a la vez según el tamaño de los
taxas involucrados en la comunidad edáfica su capacidad de afectar el
ambiente varía en diferentes escalas espacio temporales y áreas de
influencia (@lavelle2012, @briones2014)

Si bien la complejidad del suelo es enorme, su funcionamiento puede ser
entendido como un sistema auto-organizado (@lavelle_etal2006),
característica que es una propiedad emergente de los ecosistemas (odum,
whitellback (libros, papers de ecología 3)), en el que la enorme y compleja diversidad
biológica y de interacciones progresan a diferentes escalas espaciales y temporales afectando 
los procesos en el ecosistema (@lavelle2012, @brussard2004, @barrios2007), de los que dependen importantes 
servicios tales como el ciclo de los nutrientes, del carbono, del agua, la descomposición de la materia
orgánica, el mantenimiento y provisión de la fertilidad del suelo, el control de poblaciones, etc.
(@creamer2022, @briones2014) y de los que la humanidad hace uso "gratuitamente" y que en términos monetarios 
a nivel global representa trillones de dolares (@coleman_etal_2014, @fonte_etal_2023) 

En el ecosistema edáfico, las especies presentes se relacionan entre sí de diferentes maneras y estas relaciones
establecen complejas redes de interacciones (Montoya et al. 2001), cuya representación describe todas las
posibles formas en las que las especies pueden interactuar (Delmas et al. 2019; Kéfi et al. 2012) 
Estas redes de interacciones están influenciadas por factores de largo plazo tales como el clima, el suelo, la
disponibilidad de recursos e influencias biogeográficas en el grupo de especies y por factores de corto plazo
como las perturbaciones antrópicas (Kardol et al. 2016) por lo que resulta de particular interés la respuesta de
la estructura de las redes ante los distintos tipos de disturbios y su relación con el funcionamiento del
ecosistema del suelo (Sabatté, 2011; Kardol et al., 2016).
El análisis de las redes de interacciones de alimentación, e.i. redes tróficas, es el más utilizado pero incluir
todos los tipos de interacciones es fundamental para lograr un entendimiento completo sobre el funcionamiento de
los ecosistemas (Kéfi et al. 2012). 
Este análisis permite identificar especies con roles funcionales claves e identificar grupos funcionales, 
definidos como el grupo de especies con un papel semejante en el funcionamiento de un ecosistema (Gitay y Noble,
1997), también permite conocer patrones estructurales de la comunidad a partir de la topología de la red y las
consecuencias de estos patrones sobre la dinámica de una comunidad y sus especies constituyentes (Kéfi et al.
2012; Pimm et. al. 1991; Scheu 2001) y su estructura condiciona las funciones en los ecosistemas (Montoya et al. 2001; Labrador 2008)
@potapov2023 declara que el uso de las redes tróficas es una herramienta esencial que debe ser utilizada en los
ecosistemas terrestres para comprender el funcionamiento del ecosistema del suelo, ya que une los aspetos
relacionados con la diversidad específica, la diversidad funcional y los aspectos que se relacionan con la
estabilidad y resiliencia de estos sistemas.


# Recursos tróficos de la fauna edáfica

# Caracterizaciones de las comunidades del suelo estudiadas

# Espectro de tamaños

# Redes de interacciones globales

# ref

Culliney 2013 Role of Arthropods in Maintaining Soil Fertility 
Lavelle et al 2006 Soil invertebrates and ecosystem services 
Lavelle 2012 Soil as habitat. in Wall 2012 
Thakur et al 2019 Towards an integrative understanding of soil biodiversity 
Bardgett 2002 Causes and consequences of biological diversity in soil 
Creamer et al 2022 The life of soils: Integrating the who and how of multifunctionality 
Wurst et al 2012 Soil Biodiversity and Functions. En Wall 2012 
Potapov 2023 Multifunctionality of belowground food webs: resource, size and spatial energy channels
Hooper, et al 2005. Effects of biodiversity on ecosystem functioning: a consensus of current knowledge. Ecological Monographs 75: 3-35. 
Delmas et al 2019 Analysing ecological networks of species interactions
Coleman etal 2004 Fundamental of soil ecology. chap 1, Historical Overview of Soils and the Fitness
of the Soil Environment, sub section, Soils as Suppliers of Ecosystem Services pag 20
Fonte et al 2023. Earthworms contribute significantly to global food production