---
title: "soil_food_web_unlu"
author: "Velazco"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r , include=FALSE}
library(tidyverse)
```

```{r ,echo=FALSE}
#Carga datos, comunidad completa, abundancia, pesos corporales medios, 
SFW_unlu <- read.delim(
  "~/Documentos/Redes/soil_interaction_web/unlu_ab_mass_mean_web.txt"
  )
```


```{r Densidad,echo=FALSE}
#microfauna (se contaron los nemátodos de 4 sacabocados)
sup.bocado.micro <- (1/(pi*2.5^2/10000))*4
#mesofauna (se contaron y extrajeron de 3 frasquitos homojeneizados del monolito)
sup.bocado.meso <- (1/(pi*2.5^2/10000))*3
#macrofauna (superficie estandar 25 x 25)
sup.monolito <- 1/(0.25*0.25)

unlu_D<-SFW_unlu%>%
  mutate(nombre=paste(sitio,replica))%>%
           mutate(
             D=floor(case_when(
  size_class=="macro"~ sup.monolito*abundance,
  size_class=="meso"~ sup.bocado.meso*abundance,
  size_class=="micro"~ sup.bocado.micro*abundance)
  ),
  biomass=body_mass*D
  )

web<-unlu_D%>%
  group_by(nombre,sitio,replica,taxa)%>%
  summarise(body=mean(body_mass,na.rm=TRUE),
            biomass=mean(biomass,na.rm=TRUE))%>%
  distinct(taxa,.keep_all=TRUE)

```

```{r recurso_base,echo=FALSE}
#se utilizaron la biomasa estimada por m2 hasta los 5 cm

#recursos base, hongo, bacteria, protozoa
sitio<-c("L","L","L","P","P","P","R","R","R",
         "L","L","L","P","P","P","R","R","R",
         "L","L","L","P","P","P","R","R","R")
replica<-c(1,2,3,1,2,3,1,2,3,
           1,2,3,1,2,3,1,2,3,
           1,2,3,1,2,3,1,2,3)
taxa<-c("bac","bac","bac","bac","bac","bac","bac","bac","bac",
        "fungi","fungi","fungi","fungi","fungi","fungi","fungi","fungi","fungi",
        "proto","proto","proto","proto","proto","proto","proto","proto","proto")
biomass<-c(31182224/1.025,10506443/1.025,68378710/1.025,117115935/1.025,90987488/1.025,
           131508231/1.025,56295276/1.025,90096858/1.025,38740835/1.025,
          101342228/1.025,147090202/1.025,56982258/1.025,161034411/1.025,
          166810394/1.025,153426270/1.025,136717098/1.025,165177572/1.025,
          135592922/1.025,132524452*0.05,157596645*0.05,125360968*0.05,
          278150346*0.05,257797882*0.05,284934501*0.05,193012374*0.05,
          255274430*0.05,174333757*0.05)

rec_base<-data.frame(sitio,replica,taxa,biomass)
rec_base<-rec_base%>%
             mutate(
             body=case_when(
  taxa=="bac"~ 9.5e-10, #peso medio bacteria, segun digel, en ug
  taxa=="fungi"~ -999, #si considero el promedio entre ambos sería 5.560547e-05, 
                      #pero se coloca -999 cuando no hay info.
  taxa=="proto"~ 1.1121e-4)#peso medio, segun digel y en microgramos
  )
  
rec_base<-rec_base%>%
  mutate(nombre=paste(sitio,replica))

rec_base<-rec_base[,c("nombre","sitio","replica","taxa","body","biomass")]

web<-rbind(rec_base, web)

```

```{r SFW_site,echo=FALSE}
web0<-web%>%
  group_by(sitio,taxa)%>%
  summarise(body=mean(body,na.rm=TRUE),
            biomass=mean(biomass,na.rm=TRUE))%>%
  distinct(taxa,.keep_all=TRUE)

L<-web0%>%filter(sitio=="L")
P<-web0%>%filter(sitio=="P")
R<-web0%>%filter(sitio=="R")

```


```{r G_matrix, echo=FALSE}

webG<-web%>%
  group_by(taxa)%>%
  distinct(taxa,.keep_all=TRUE)

#print(R$taxa)
sp_G<-c("litter","carrion","tej_veg","hummus",levels(as.factor(webG$taxa)))
mG<-matrix(nrow = length(sp_G),ncol = length(sp_G),
           dimnames = list(sp_G,sp_G))
#reemplazar NA por ceros

mG[is.na(mG)] <- 0
#####
#Microflora
mG["bac",c("hummus","litter","carrion")]<-1
mG["fungi",c("hummus","tej_veg","carrion","litter")]<-1
#Microfauna
mG["proto",c("bac","hummus","proto")]<-1
mG["enchytraeida",c("bac","hummus","proto","fungi")]<-1
mG["nem_predador",c("nem_predador","nem_omnivor","nem_fitofago",
                    "nem_bacterivoro","nem_fungivoro","proto","tardigrado")]<-1
mG["nem_omnivor",c("nem_predador","nem_omnivor","nem_fitofago",
                   "nem_bacterivoro","nem_fungivoro","proto",
                   "tardigrado","bac","fungi")]<-1
mG["nem_fitofago",c("tej_veg")]<-1
mG["nem_fungivoro",c("fungi")]<-1
mG["nem_bacterivoro",c("bac")]<-1

#lombrices
mG[c("juvenil","Aporrectodea caliginosa",
     "Aporrectodea rosea","Aporrectodea trapezoides",
     "Bimastos beddardi sophiae","Bimastos parvus",
     "Eukerria halophila","Glossoscolex sp.",
     "Microscolex phosphoreus","Octalasion cyaneum","Octolasion tyrtaeum"),
   c("litter","bac","fungi","proto","hummus")]<-1

mG["astigmata",c("bac","fungi","nem_fitofago",
                    "nem_bacterivoro","nem_fungivoro","proto")]<-1

mG["limnozetidae",c("bac","fungi")]<-1

mG["coccinelidae",c("aphidoidea","thysanoptera","terebrantia","cicadidae")]

mG[c("aphidoidea","coleoptera_suctor","thysanoptera","hemiptero",
     "cicadidae","ortoptero","terebrantia","embrioptera"),
   c("tej_veg")]<-1 #este aparece, pero tal vez no se alimente¿?

#grandes detritivoros
mG[c("oniscidea","blattodea","diplopoda","gasteropoda",
     "larva_coleoptero","larva_tenebrionidae","larva_curculionidae","larva_diptera",
     "larva_elateridae","larva_scarabidae","larva_sciaridae",
     "pupa_diptera","trogossitidae","cryptophagidae",
     "ptilidae","elateriforme","tenebrionidae","anthribidae"),
   c("fungi","litter","carrion")]<-1

#Grandes mesostigmatas
#arctacaridae in the review not information of this group
#Krantz say " it may represent the sister group of the gamasine subcohorrs 
# Parasitiae and Dermanyssiae, 
#eviphididae, laelapidae, ologamasidae, parasitidae, veigaioidea

mG[c("ameroseidae","arctacaridae","dermanisoidea","eviphididae", 
     "ichtyostomatogasteridae","laelapidae","ologamasidae", 
     "parasitidae", "veigaioidea"),
   c("enchytraeida","nem_predador","nem_omnivor","nem_fitofago",
                   "nem_bacterivoro","nem_fungivoro","proto","astigmata",
                   "limnozetidae","ceratozetoidea","diplura","entomobridae",
                   "epilhomanioidea","eremobelbidae","eupthiracaroidea",
                   "galumnidae","hipogastruridae","isotomidae","larva_diptera",
                   "larva_sciaridae","onichiuridae","oppioidea","oribatulidae",
                   "oripodidae","protura", "scheloribatidae","symphyla",
                   "symphypleona", "teneriffidae","tardigrado",
     "alycidae", "anystidae","macropilina")]<-1



mG[c("bdelloidea","penthalidae","cunaxide","trombidiidae"),
   c("enchytraeida","nem_predador","nem_omnivor","nem_fitofago",
                   "nem_bacterivoro","nem_fungivoro","proto","astigmata",
                   "limnozetidae","ceratozetoidea","diplura","entomobridae",
                   "epilhomanioidea","eremobelbidae","eupthiracaroidea",
                   "galumnidae","hipogastruridae","isotomidae","mesostigmata",
                  "onichiuridae","oppioidea","oribatulidae",
                   "oripodidae","protura", "scheloribatidae","symphyla",
                   "symphypleona", "teneriffidae","rhodacarioidea","tardigrado",
                  "rhagidiidae","alycidae", "anystidae","macropilina"
                  )]<-1

mG[c("carabidae","staphiliniidae"),
   c("enchytraeida","astigmata","limnozetidae","ceratozetoidea",
                 "diplura","entomobridae",
                   "epilhomanioidea","eremobelbidae","eupthiracaroidea","eupodoidea",
                   "eviphididae","galumnidae","hipogastruridae","isotomidae",
                 "mesostigmata","laelapidae",
                 "larva_diptera","larva_sciaridae",
                 "ologamasidae","parasitidae","bdelloidea",
                 "onichiuridae","oppioidea","oribatulidae",
                   "oripodidae","protura", "scheloribatidae","symphyla",
                   "symphypleona", "teneriffidae","rhodacarioidea","tardigrado",
                  "rhagidiidae","tydeioidea","uropodoidea","veigaioidea","arctacaridae",
                 "bdelloidea","penthalidae","cunaxide","trombidiidae",
                 "ameroseidae","arctacaridae","dermanisoidea", 
     "ichtyostomatogasteridae","macropilina","eupodoidea","tydeioidea","alycidae",
     "anystidae","tarsonemidae","teneriffidae")]<-1


mG["larva_carabidae",c("enchytraeida","nem_predador","nem_omnivor","nem_fitofago",
                   "nem_bacterivoro","nem_fungivoro","proto")]<-1



mG["geophylomorpha",c("alycidae","anystidae","ameroseidae","bdelloidea","cunaxide",
                      "arctacaridae","enchytraeida","astigmata","limnozetidae",
                      "ceratozetoidea", "diplura","entomobridae",
                      "dermanisoidea","ichtyostomatogasteridae","macropilina",
                   "epilhomanioidea","eremobelbidae","eupthiracaroidea","eupodoidea",
                   "eviphididae","galumnidae","hipogastruridae","isotomidae",
                 "mesostigmata","laelapidae","larva_coleoptero","larva_curculionidae",
                 "larva_diptera","larva_elateridae","larva_sciaridae",
                 "ologamasidae","parasitidae","blattodea","carabidae",
                 "onichiuridae","oppioidea","oribatulidae","penthalidae",
                   "oripodidae","protura", "scheloribatidae","symphyla",
                   "symphypleona", "teneriffidae","rhodacarioidea","tardigrado",
                  "rhagidiidae","tydeioidea","uropodoidea","veigaioidea",
                 "aphidoidea","cicadidae","coleoptera_suctor","cryptophagidae",
                 "diplopoda","juvenil","elateriforme","hemiptero","larva_carabidae",
                 "ptilidae","staphiliniidae","thysanoptera","trogossitidae",
                   "tarsonemidae","tenebrionidae","terebrantia","trombidiidae"
                  )]<-1

mG["grillopalpidae",c("carrion","bac","fungi","tej_veg","enchytraeida",
                      "nem_predador","nem_omnivor","nem_fitofago",
                   "nem_bacterivoro","nem_fungivoro","proto",
                   "diplura","entomobridae","hipogastruridae","isotomidae",
                  "onichiuridae","oppioidea","oripodidae","protura",
                  "symphyla","symphypleona","rhodacarioidea","tardigrado"
                  )]<-1

mG[c("ceratozetoidea","onichiuridae","isotomidae","macropilina",
     "scheloribatidae","oripodidae","oribatulidae",
     "protura","symphyla","eremobelbidae"),c("bac","fungi","hummus")]<-1

mG["symphypleona",c("bac","fungi","hummus","tej_veg","litter")]<-1

mG["entomobridae",c("bac","fungi","nem_bacterivoro","nem_fungivoro")]<-1

mG[c("epilhomanioidea","eupthiracaroidea"),c("hummus","fungi","tej_veg")]<-1

mG[c("eupodoidea","tydeioidea","alycidae","anystidae","tarsonemidae"),
   c("bac","fungi","nem_predador","nem_omnivor","nem_fitofago",
                   "nem_bacterivoro","nem_fungivoro","proto","tardigrado",
                  "onichiuridae","hipogastruridae","isotomidae","symphypleona",
                  "entomobridae","symphyla","protura","diplura")]<-1

mG["formicidae",c("carrion","fungi","tej_veg",
                  "Aporrectodea caliginosa","Aporrectodea rosea",
                  "Aporrectodea trapezoides","Bimastos beddardi sophiae",
                  "Eukerria halophila","Glossoscolex sp.",
                  "Bimastos parvus","arctacaridae","enchytraeida",
                  "astigmata","limnozetidae","embrioptera","grillopalpidae",
                  "macropilina","Microscolex phosphoreus",
                  "Octalasion cyaneum","Octolasion tyrtaeum","ortoptero","penthalidae",
                      "ceratozetoidea", "diplura","entomobridae",
                   "epilhomanioidea","eremobelbidae","eupthiracaroidea","eupodoidea",
                   "eviphididae","galumnidae","hipogastruridae","isotomidae",
                 "mesostigmata","laelapidae","larva_coleoptero","larva_curculionidae",
                 "larva_diptera","larva_elateridae","larva_sciaridae",
                 "ologamasidae","parasitidae","bdelloidea","blattodea","carabidae",
                 "onichiuridae","oppioidea","oribatulidae","pupa_diptera",
                   "oripodidae","protura", "scheloribatidae","symphyla",
                   "symphypleona", "teneriffidae","rhodacarioidea",
                  "rhagidiidae","tydeioidea","uropodoidea","veigaioidea",
                 "aphidoidea","cicadidae","coleoptera_suctor","cryptophagidae",
                 "diplopoda","juvenil","elateriforme","hemiptero","larva_carabidae",
                 "ptilidae","staphiliniidae","thysanoptera","trogossitidae",
                 "alycidae","ameroseidae","anthribidae","anystidae","coccinelidae",
                 "tenebrionidae","terebrantia"
                  )]<-1



mG["galumnidae",c("carrion","nem_fitofago","tardigrado",
                   "nem_bacterivoro","nem_fungivoro","proto","bac","fungi")]<-1

mG["hipogastruridae",c("nem_predador","nem_omnivor","nem_fitofago",
                   "nem_bacterivoro","nem_fungivoro","proto",
                   "tardigrado","bac","fungi","carrion")]<-1

mG[c("linyphiidae","lycosidae","pseudoscorpionida"),
   c("coccinelidae","aphidoidea","arctacaridae","astigmata",
     "limnozetidae","blattodea","carabidae","grillopalpidae",
     "ceratozetoidea","cicadidae","coleoptera_suctor","cryptophagidae",
     "cunaxide","diplura","elateriforme","entomobridae",
     "eremobelbidae","eupodoidea","eviphididae","macropilina","ortoptero",
     "formicidae","galumnidae","geophylomorpha","penthalidae","tenebrionidae",
     "hemiptero","hipogastruridae","isotomidae",
     "laelapidae","mesostigmata","ologamasidae",
     "oribatulidae","oripodidae","parasitidae",
     "ptilidae","staphiliniidae","symphyla","dermanisoidea",
     "symphypleona","thysanoptera","trogossitidae",
     "tydeioidea","uropodoidea","veigaioidea","anthribidae",
     "embrioptera","terebrantia","trombidiidae"
     )]<-1

mG["mesostigmata",c("nem_predador","nem_omnivor","nem_fitofago",
                   "nem_bacterivoro","nem_fungivoro","proto","tardigrado")]<-1

mG["oppioidea",c("bac","fungi","hummus")]<-1

mG[c("protura","diplura","symphyla"),c("carrion","bac","fungi","proto")]<-1

mG["ptilidae",c("hummus","fungi","carrion","bac","proto","nem_fitofago",
                   "nem_bacterivoro","nem_fungivoro")]<-1

mG[c("rhodacarioidea","teneriffidae","rhagidiidae"),
   c("nem_predador","nem_omnivor","nem_fitofago",
                   "nem_bacterivoro","nem_fungivoro","proto","tardigrado",
                   "onichiuridae","hipogastruridae","isotomidae","symphypleona",
                   "protura","diplura","symphyla",
                   "entomobridae","enchytraeida")]<-1

mG["nematomorpha",c("aphidoidea","blattodea","carabidae",
    "cicadidae","coleoptera_suctor","cryptophagidae",
    "elateriforme","geophylomorpha","hemiptero",
    "ptilidae","staphiliniidae","thysanoptera","trogossitidae")]<-1


mG["uropodoidea",c("nem_predador","nem_omnivor","nem_fitofago",
                   "nem_bacterivoro","nem_fungivoro","proto","tardigrado")]<-1

```


```{r R, echo=FALSE}
{library(statnet);library(network);library(igraph);library(intergraph);
  library(multiweb)}

#red gamma
G_net<-network(t(mG),vertex.attrnames=sp_G)
#red LOTE
L_net<-network(t(mG[L$taxa,L$taxa]),vertex.attrnames=rownames((mG[L$taxa,L$taxa])))
#red RESERVA
R_net<-network(t(mG[R$taxa,R$taxa]),vertex.attrnames=rownames((mG[R$taxa,R$taxa])))
#red PASTIZAL
P_net<-network(t(mG[P$taxa,P$taxa]),vertex.attrnames=rownames((mG[P$taxa,P$taxa])))
```


```{r L_mx,echo=FALSE}


```

