---

output:
  html_document: default

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
loadNamespace('printr')
options("digits"=3)
```

```{r lib, include=FALSE, warning=FALSE}
#Carga paquetes
{library("tidyverse");library("readxl");library("ade4");library("Hmisc");
library("vegan");library("cluster");library("BiodiversityR") 
library("FactoMineR");library("factoextra"); library("kableExtra")}
set.seed(167)

```

## Resultados

```{r carga_variablesFQB, include=FALSE, warning=FALSE}

fyq_unlu <- read.delim("database/fyq_unlu.txt")

####
# Respiración heterotrófica
# Valores expresados en miligramos de CO2/h/100g suelo

resp.b<-c( 0.131588785046729,0.14803738317757,0.14803738317757, #Pastizal
           0.188187372708758,0.15234215885947,0.170264765784114, #Reserva
           0.066236559139785,0.0851612903225806,0.0946236559139785) #Agrícola


# Relación de hongos : bacterias

#pasar las relaciones decimales a fracción
ratio.hb<-c( 11/8, 11/6, 7/6, #Pastizal
            2.42857142857143, 11/6, 3.5, #Reserva
                       3.25, 14/3, 5/6) #Agrícola

#Agrícola, corrección de 14 por 4.66 (como? usando la biomasa residual)
# en agrícola existe un valor atípico de 14 y lo corregi a 1.4

#hojarasca g/m2
h<-c(
  160.59*0.5*16, #P
147.55*0.5*16,
144.48*0.5*16,

200.324*0.55*16, #R
77.736*0.55*16,
135.25*0.55*16,

173.93*0.3*16, #A
81.38*0.3*16,
259.77*0.3*16)*0.3





#########
# matrices fisicoquimicas
fyq.box<-fyq_unlu%>%mutate(
  sistema=substr(Sitio, 3, 3),
                       estrato=substr(Sitio, 1, 2),
                       replica=substr(Sitio, 4, 4),
 )
names(fyq.box)<-c("nombre","muestra","CE","pH","MO","C","P","N","TOC","D_TOC_C","C_TOC","sitio","estrato","replica")
#se eligen las variables de interés

fyq.box<-fyq.box[,c(1,12,14,13,3,4,5,8,7)]

fqb.box<-data.frame(resp.b,ratio.hb,h,sitio=c(rep("P",3),rep("R",3),rep("A",3)),estrato=rep(10,9))

```

```{r carga_variables_fqb_RO, include=FALSE, warning=FALSE}
#Anális de datos de ROSANA
#Carga de datos

RO <-RO <- read_excel("database/soil_networks.xlsx", sheet = "Ro_web")
RO[is.na(RO)]<-0

#Filtrar la macrofauna, razon, el diseño de muestreo no lo contempla

RO_f<-RO %>% filter(class!="macrofauna")%>%
  mutate(nombre=paste(system,
                                    substr(site,1,3),
                                    substr(year,3,4),
                                    substr(month,1,3)))%>%
  group_by(nombre,
           system,site,year,month,season,
           order,guild,specie) %>%
  summarise(abundance=n(), peso.ind=median(biomass), 
            bmicro=(median(bm)), 
            res.mec=median((RM5+RM10)/2),DAP=median(DAP),HR=median(HR),
            pH=median(Ph),CE=median(CE),
            MO=median(MO),N=median(N),P=median(P),K=median(K),
            Ca=median(Ca),Mg=median(Mg),Na=median(Sodio),respH=mean(RESP))%>%
  distinct(specie,.keep_all=TRUE)

#Llevando abundancias a densidad####

sup.bocado <- 1/(pi*2.5^2/10000)
sup.monolito <- 1/(0.25*0.25)


RO_full<-RO_f%>%mutate(D=floor(case_when(
  order=="crassiclitellata"~sup.monolito*abundance,
  order!="crassiclitellata"~sup.bocado*abundance)
  ),BT=D*peso.ind)


#Matriz de comunidad####

abund_RO<-RO_full[,c("nombre","system","site","specie","abundance","D")] %>% 
  pivot_wider(names_from = specie,
              values_from = c(abundance,D),
              values_fill = 0,
              values_fn = sum)%>%
  distinct(nombre,.keep_all=TRUE)

#Matriz fisico quimica#########
fq_RO<-RO_full%>%group_by(nombre,
           system,site,year,month,season,
           )%>%
  summarise(res.mec=mean(res.mec),DAP=mean(DAP),HR=mean(HR),
            pH=mean(pH),CE=mean(CE),
            MO=mean(MO),N=mean(N),P=mean(P),K=mean(K),
            Ca=mean(Ca),Mg=mean(Mg),Sodio=mean(Na),rH=mean(respH))%>%
  distinct(nombre,.keep_all=TRUE)
#Asignar número de réplica según la tesis de Rosana. pp53 tabla 2.1.
#En el espectro de tamaños esto se encuentra con sus nombres.
fq_RO$replica
fq_RO[fq_RO$site=="triangulo","replica"]<-1
fq_RO[fq_RO$site=="L27","replica"]<-1
fq_RO[fq_RO$site=="molino","replica"]<-1

fq_RO[fq_RO$site=="festuca","replica"]<-2
fq_RO[fq_RO$site=="L24","replica"]<-2
fq_RO[fq_RO$site=="manga","replica"]<-2

fq_RO[fq_RO$site=="romina","replica"]<-3
fq_RO[fq_RO$site=="L25","replica"]<-3
fq_RO[fq_RO$site=="casuarina","replica"]<-3

#En esta matriz de datos completa se encuentra la réplica, no se incluye
# los pesos corporales, será trabajada en la próxima sección
# cada sitio con sus variables FyQ y con las especies con densidad y abundancias

RO_db_full <- merge(fq_RO, abund_RO, by = "nombre", all = TRUE)
name.RO_db_full<-c(names(RO_db_full))

names(RO_db_full)<-c("nombre","system","site",name.RO_db_full[-c(1:3)])

```

```{r matriz_pca, include=FALSE}

fyq.pca<-fyq_unlu%>%mutate(sitio=substr(Sitio, 3, 3),
                       estrato=substr(Sitio, 1, 2),
                       replica=substr(Sitio, 4, 4),
                       nombre=paste(sitio,replica))%>%
  group_by(sitio,replica,nombre)%>%
  summarise(CE=mean(CE..Ms.,na.rm=TRUE),CE.sd=sd(CE..Ms.,na.rm=TRUE),
            pH=mean(PH,na.rm=TRUE),pH.sd=sd(PH,na.rm=TRUE),
            MO=mean(MATERIA.ORGÁNICA,na.rm=TRUE),MO.sd=sd(MATERIA.ORGÁNICA,na.rm=TRUE),
            C=mean(CARBONO,na.rm=TRUE),C.sd=sd(CARBONO,na.rm=TRUE),
            TOC=mean(TOC,na.rm=TRUE),TOC.sd=sd(TOC,na.rm=TRUE),
            N=mean(NITRÓGENO,na.rm=TRUE),N.sd=sd(NITRÓGENO,na.rm=TRUE),
            P=mean(FÓSFORO,na.rm=TRUE),P.sd=sd(FÓSFORO,na.rm=TRUE))%>%
  distinct(nombre,.keep_all=TRUE)

#agrego respiración en CO2/h/g
fyq.pca$resp.b<-c(0.066236559139785,0.0851612903225806,0.0946236559139785,
                    0.131588785046729,0.14803738317757,0.14803738317757,
                    0.188187372708758,0.15234215885947,0.170264765784114)
#agrego relación Hongo-Bacterias
fyq.pca$ratio.hb<-c(3.25, 1.400000000001, 0.833333333333333,
                       1.375, 1.83333333333333, 1.16666666666667,
                       2.42857142857143, 1.83333333333333, 3.5)
#Valores expresados en microgramos de C-biomasa/g suelo
fyq.pca$ug_biom_x_g<-c(1.80305376344086, 2.14417204301075, 1.70559139784947,
3.78435845213849, 3.50745417515275, 3.87665987780041, 2.62601869158878,
3.4731214953271, 2.37188785046729)*1000


# con la idea de tener la cantidad de hongos y bacterias
# densidad aparente 1,47 g/cm3 (sacado del promedio pastura, agricola, reserva, tesina
#Veronica)
# suelo a 5 cm en un m2 son 50k cm3 aprox 0.5m3, esto es, 73500 g en 0.5m3 suelo 
# más factor 1e6 para microgramos


fyq.pca$bio.micro<-fyq.pca$ug_biom_x_g*73500


fyq.pca$fungi<-round(fyq.pca$bio.micro*(fyq.pca$ratio.hb/(fyq.pca$ratio.hb+1)),4)
fyq.pca$bacteria<-round((fyq.pca$bio.micro-fyq.pca$fungi),4)
hj<-c(80.6664*16, 46.009*16, 104.421*16,#A
  70.85*16,44.15*16,60.9*16,#P
48.81*16,64.319*16,54.13*16 #R
) 
fyq.pca$hojarasca<-hj

#write.table(unlu_merg[,c(1,2,3,4,6,8,10,12,14,16,258:263,20:138)],"matrizunlu.txt")

```

```{r corFQB_unlu, echo=FALSE}
fq1<-fyq.pca[,c(6,8,14,16,18,19,24)]
fq1<-as.data.frame(fq1)
row.names(fq1)<-fyq.pca$nombre

corr_fqb_unlu<-Hmisc::rcorr(as.matrix(fq1),type = "spearman");
p_unlu<-(round(as.matrix(corr_fqb_unlu$P),2))
r_unlu<-(round(as.matrix(corr_fqb_unlu$r),2))

corr_unlu <- matrix(NA, nrow = ncol(fq1), ncol = ncol(fq1), dimnames = list(c("pH","% MO","% N", "P (ppm)", "Resp. Heterotrófica", "Hongos/Bacterias", "Hojarasca"),c("pH","% MO","% N", "P (ppm)", "Resp. Heterotrófica", "Hongos/Bacterias", "Hojarasca")))
corr_unlu[upper.tri(corr_unlu, diag = FALSE)] <- p_unlu[upper.tri(p_unlu, diag = FALSE)]
corr_unlu[lower.tri(corr_unlu,diag = TRUE)] <- r_unlu[lower.tri(r_unlu,diag = TRUE)]

corrRO<-Hmisc::rcorr(as.matrix(RO_db_full[,c(10,12:14,19)]),type = "spearman")

p_ro<-(round(as.matrix(corrRO$P),2))
r_ro<-(round(as.matrix(corrRO$r),2))

corr_ro <- matrix(NA, nrow = ncol(RO_db_full[,c(10,12:14,19)]), ncol = ncol(RO_db_full[,c(10,12:14,19)]), dimnames = list(c("pH","% MO","% N", "P (ppm)", "Resp. Heterotrófica"),c("pH","% MO","% N", "P (ppm)", "Resp. Heterotrófica")))
corr_ro[upper.tri(corr_ro)] <- p_ro[upper.tri(p_ro)]
corr_ro[lower.tri(corr_ro,diag = TRUE)] <- r_ro[lower.tri(r_ro,diag = TRUE)]

#corrplot::corrplot(cor(fq1),tl.pos="t",type = "upper",tl.col = "black",tl.cex = .8,bg="brown4",diag=FALSE)
#col=col3(100),

# PerformanceAnalytics::chart.Correlation(as.matrix(fq1), histogram = TRUE, method = "spearman")
```

**A)**

```{r corrFQB_unlu, echo=FALSE, message=FALSE,warning=FALSE}
corr_unlu

```

**B)**

```{r corrFQB_ro, echo=FALSE, message=FALSE,warning=FALSE}

corr_ro
```


```{r fq.tab,include=FALSE,message=FALSE,warning=FALSE}
#tabla fq######

fq.tab<-data.frame(Sitio=c("R","P","A","N","G","A"),
                   pH=c(
                     paste(sep=" ",
                        round(mean(fyq.box[fyq.box$sitio=="R","pH"],na.rm=TRUE),1),
                        "±",
                        round(sd(fyq.box[fyq.box$sitio=="R","pH"],na.rm=TRUE),2)),
                     paste(sep=" ",
                        round(mean(fyq.box[fyq.box$sitio=="P","pH"],na.rm=TRUE),1),
                        "±",
                        round(sd(fyq.box[fyq.box$sitio=="P","pH"],na.rm=TRUE),2)),
                     paste(sep=" ",
                        round(mean(fyq.box[fyq.box$sitio=="A","pH"],na.rm=TRUE),1),
                        "±",
                        round(sd(fyq.box[fyq.box$sitio=="A","pH"],na.rm=TRUE),2)),
                     paste(sep=" ",
                       round(mean(RO_db_full[RO_db_full$system=="N","pH"],na.rm=TRUE),1),
                        "±",
                        round(sd(RO_db_full[RO_db_full$system=="N","pH"],na.rm=TRUE),2),"a"),
                     paste(sep=" ",
                       round(mean(RO_db_full[RO_db_full$system=="G","pH"],na.rm=TRUE),1),
                        "±",
                        round(sd(RO_db_full[RO_db_full$system=="G","pH"],na.rm=TRUE),2),"b"),
                     paste(sep=" ",
                       round(mean(RO_db_full[RO_db_full$system=="A","pH"],na.rm=TRUE),1),
                        "±",
                        round(sd(RO_db_full[RO_db_full$system=="A","pH"],na.rm=TRUE),2),"b")
                     ),
                     
                     MO=c(
                     paste(sep=" ",
                        round(mean(fyq.box[fyq.box$sitio=="R","MO"],na.rm=TRUE),1),
                        "±",
                        round(sd(fyq.box[fyq.box$sitio=="R","MO"],na.rm=TRUE),2)),
                     paste(sep=" ",
                        round(mean(fyq.box[fyq.box$sitio=="P","MO"],na.rm=TRUE),1),
                        "±",
                        round(sd(fyq.box[fyq.box$sitio=="P","MO"],na.rm=TRUE),2)),
                     paste(sep=" ",
                        round(mean(fyq.box[fyq.box$sitio=="A","MO"],na.rm=TRUE),1),
                        "±",
                        round(sd(fyq.box[fyq.box$sitio=="A","MO"],na.rm=TRUE),2)),
                     paste(sep=" ",
                       round(mean(RO_db_full[RO_db_full$system=="N","MO"],na.rm=TRUE),1),
                        "±",
                        round(sd(RO_db_full[RO_db_full$system=="N","MO"],na.rm=TRUE),2)),
                     paste(sep=" ",
                       round(mean(RO_db_full[RO_db_full$system=="G","MO"],na.rm=TRUE),1),
                        "±",
                        round(sd(RO_db_full[RO_db_full$system=="G","MO"],na.rm=TRUE),2)),
                     paste(sep=" ",
                       round(mean(RO_db_full[RO_db_full$system=="A","MO"],na.rm=TRUE),1),
                        "±",
                        round(sd(RO_db_full[RO_db_full$system=="A","MO"],na.rm=TRUE),2))
),
                N=c(
                     paste(sep=" ",
                        round(mean(fyq.box[fyq.box$sitio=="R","N"]/10,na.rm=TRUE),1),
                        "±",
                        round(sd(fyq.box[fyq.box$sitio=="R","N"]/10,na.rm=TRUE),2)),
                     paste(sep=" ",
                        round(mean(fyq.box[fyq.box$sitio=="P","N"]/10,na.rm=TRUE),1),
                        "±",
                        round(sd(fyq.box[fyq.box$sitio=="P","N"]/10,na.rm=TRUE),2)),
                     paste(sep=" ",
                        round(mean(fyq.box[fyq.box$sitio=="A","N"]/10,na.rm=TRUE),1),
                        "±",
                        round(sd(fyq.box[fyq.box$sitio=="A","N"]/10,na.rm=TRUE),2)),
                     paste(sep=" ",
                       round(mean(RO_db_full[RO_db_full$system=="N","N"],na.rm=TRUE),1),
                        "±",
                        round(sd(RO_db_full[RO_db_full$system=="N","N"],na.rm=TRUE),2)),
                     paste(sep=" ",
                       round(mean(RO_db_full[RO_db_full$system=="G","N"],na.rm=TRUE),1),
                        "±",
                        round(sd(RO_db_full[RO_db_full$system=="G","N"],na.rm=TRUE),2)),
                     paste(sep=" ",
                       round(mean(RO_db_full[RO_db_full$system=="A","N"],na.rm=TRUE),1),
                        "±",
                        round(sd(RO_db_full[RO_db_full$system=="A","N"],na.rm=TRUE),2))
),
                                   P=c(
                     paste(sep=" ",
                        round(mean(fyq.box[fyq.box$sitio=="R","P"],na.rm=TRUE),1),
                        "±",
                        round(sd(fyq.box[fyq.box$sitio=="R","P"],na.rm=TRUE),2),"b"),
                     paste(sep=" ",
                        round(mean(fyq.box[fyq.box$sitio=="P","P"],na.rm=TRUE),1),
                        "±",
                        round(sd(fyq.box[fyq.box$sitio=="P","P"],na.rm=TRUE),2),"b"),
                     paste(sep=" ",
                        round(mean(fyq.box[fyq.box$sitio=="A","P"],na.rm=TRUE),1),
                        "±",
                        round(sd(fyq.box[fyq.box$sitio=="A","P"],na.rm=TRUE),2),"a"),
                     paste(sep=" ",
                       round(mean(RO_db_full[RO_db_full$system=="N","P"],na.rm=TRUE),1),
                        "±",
                        round(sd(RO_db_full[RO_db_full$system=="N","P"],na.rm=TRUE),2)),
                     paste(sep=" ",
                       round(mean(RO_db_full[RO_db_full$system=="G","P"],na.rm=TRUE),1),
                        "±",
                        round(sd(RO_db_full[RO_db_full$system=="G","P"],na.rm=TRUE),2)),
                     paste(sep=" ",
                       round(mean(RO_db_full[RO_db_full$system=="A","P"],na.rm=TRUE),1),
                        "±",
                        round(sd(RO_db_full[RO_db_full$system=="A","P"],na.rm=TRUE),2))
)
)

#lista KW####
kw_fq<-list(kruskal.test(pH ~ sitio, data = fyq.box),
            pairwise.wilcox.test(fyq.box$pH, fyq.box$sitio,data=fyq.box,
                                          p.adjust.method = "BH",exact=FALSE),
kruskal.test(pH ~ system, data = RO_db_full),
pairwise.wilcox.test(RO_db_full$pH, RO_db_full$sitio,data=RO_db_full,
                                          p.adjust.method = "BH",exact=FALSE),
kruskal.test(MO ~ sitio, data = fyq.box),
pairwise.wilcox.test(fyq.box$MO, fyq.box$sitio,data=fyq.box,
                     p.adjust.method = "BH",exact=FALSE),
kruskal.test(MO ~ system, data = RO_db_full),
pairwise.wilcox.test(RO_db_full$MO, RO_db_full$system,data=RO_db_full,
                                          p.adjust.method = "BH",exact=FALSE),
kruskal.test(N ~ sitio, data = fyq.box),
pairwise.wilcox.test(fyq.box$N, fyq.box$sitio,data=fyq.box,
                     p.adjust.method = "BH",exact=FALSE),
kruskal.test(N ~ system, data = RO_db_full),
pairwise.wilcox.test(RO_db_full$N, RO_db_full$system,data=RO_db_full,
                                          p.adjust.method = "BH",exact=FALSE),
kruskal.test(P ~ sitio, data = fyq.box),
pairwise.wilcox.test(fyq.box$P, fyq.box$sitio,data=fyq.box,
                     p.adjust.method = "BH",exact=FALSE),
kruskal.test(P ~ system, data = RO_db_full),
pairwise.wilcox.test(RO_db_full$P, RO_db_full$system,data=RO_db_full,
                                          p.adjust.method = "BH",exact=FALSE)
)


```


```{r fq.tabA,echo=FALSE,message=FALSE,warning=FALSE}
#mostrar tab####
fq.tab
```

```{r resp.tab,include=FALSE,message=FALSE,warning=FALSE}
#tabla respiracion####
resp.tab<-data.frame(Sitio=c("R","P","A","N","G","A"),
                   resp=c(    paste(sep=" ",
                        round(mean(fqb.box[fqb.box$sitio=="R","resp.b"],na.rm=TRUE),3),
                        "±",
                        round(sd(fqb.box[fqb.box$sitio=="R","resp.b"],na.rm=TRUE),3),"a"),
                     paste(sep=" ",
                        round(mean(fqb.box[fqb.box$sitio=="P","resp.b"],na.rm=TRUE),3),
                        "±",
                        round(sd(fqb.box[fqb.box$sitio=="P","resp.b"],na.rm=TRUE),3),"b"),
                     paste(sep=" ",
                        round(mean(fqb.box[fqb.box$sitio=="A","resp.b"],na.rm=TRUE),3),
                        "±",
                        round(sd(fqb.box[fqb.box$sitio=="A","resp.b"],na.rm=TRUE),3),"c"),
                     paste(sep=" ",
                       round(mean(RO_db_full[RO_db_full$system=="N","rH"],na.rm=TRUE),3),
                        "±",
                        round(sd(RO_db_full[RO_db_full$system=="N","rH"],na.rm=TRUE),3),"a"),
                     paste(sep=" ",
                       round(mean(RO_db_full[RO_db_full$system=="G","rH"],na.rm=TRUE),3),
                        "±",
                        round(sd(RO_db_full[RO_db_full$system=="G","rH"],na.rm=TRUE),3),"a"),
                     paste(sep=" ",
                       round(mean(RO_db_full[RO_db_full$system=="A","rH"],na.rm=TRUE),3),
                        "±",
                        round(sd(RO_db_full[RO_db_full$system=="A","rH"],na.rm=TRUE),3),"b")
                 ),
                 H_B=c(    paste(sep=" ",
                        round(mean(fqb.box[fqb.box$sitio=="R","ratio.hb"],na.rm=TRUE),2),
                        "±",
                        round(sd(fqb.box[fqb.box$sitio=="R","ratio.hb"],na.rm=TRUE),2)),
                     paste(sep=" ",
                        round(mean(fqb.box[fqb.box$sitio=="P","ratio.hb"],na.rm=TRUE),2),
                        "±",
                        round(sd(fqb.box[fqb.box$sitio=="P","ratio.hb"],na.rm=TRUE),2)),
                     paste(sep=" ",
                        round(mean(fqb.box[fqb.box$sitio=="A","ratio.hb"],na.rm=TRUE),2),
                        "±",
                        round(sd(fqb.box[fqb.box$sitio=="A","ratio.hb"],na.rm=TRUE),2)),
                     paste(sep=" ","-"),
                     paste(sep=" ","-"),
                     paste(sep=" ","-")
                 ),
                 Hoj=c(    paste(sep=" ",
                        round(mean(fqb.box[fqb.box$sitio=="R","h"],na.rm=TRUE),2),
                        "±",
                        round(sd(fqb.box[fqb.box$sitio=="R","h"],na.rm=TRUE),2)),
                     paste(sep=" ",
                        round(mean(fqb.box[fqb.box$sitio=="P","h"],na.rm=TRUE),2),
                        "±",
                        round(sd(fqb.box[fqb.box$sitio=="P","h"],na.rm=TRUE),2)),
                     paste(sep=" ",
                        round(mean(fqb.box[fqb.box$sitio=="A","h"],na.rm=TRUE),2),
                        "±",
                        round(sd(fqb.box[fqb.box$sitio=="A","h"],na.rm=TRUE),2)),
                     paste(sep=" ","-"),
                     paste(sep=" ","-"),
                     paste(sep=" ","-")
                 )
                     ,row.names = NULL)
#lista kw####
kw_resp<-list(kruskal.test(resp.b ~ sitio, data = fqb.box),
            pairwise.wilcox.test(fqb.box$resp.b, fqb.box$sitio,data=fyq.box,
                                          p.adjust.method = "BH",exact=FALSE),
            kruskal.test(rH ~ system, data = RO_db_full),
pairwise.wilcox.test(RO_db_full$rH, RO_db_full$system,data=RO_db_full,
                                          p.adjust.method = "BH",exact=FALSE),
kruskal.test(ratio.hb ~ sitio, data = fqb.box),
            pairwise.wilcox.test(fqb.box$ratio.hb, fqb.box$sitio,data=fqb.box,
                                          p.adjust.method = "BH",exact=FALSE),
kruskal.test(h ~ sitio, data = fqb.box),
            pairwise.wilcox.test(fqb.box$h, fqb.box$sitio,data=fqb.box,
                                          p.adjust.method = "BH",exact=FALSE))

```

```{r resp.tabB,echo=FALSE,message=FALSE,warning=FALSE}
#print####
colnames(resp.tab)<-c("Sitio", "Respiración heterotrófica", "Hongo:Bacteria", "Hojarasca")
resp.tab

```



```{r PCA, include=FALSE, warning=FALSE}
names(fq1)<-c("pH","MO","N", "P", "R-H", "H/B", "Hoj")
  
#c("pH","% MO","% N", "P (ppm)", "Resp. Heterotrófica", "Hongos/Bacterias", "Hojarasca")

#No se transformará solo dejar para las comunidades
unlu_pcaFQB<-PCA(fq1, scale.unit = TRUE, graph = FALSE)

print(summary(unlu_pcaFQB))

#print(unlu_pcaFQB$eig)

print(unlu_pcaFQB$eig[1:4, c(1,3)])

print(round(unlu_pcaFQB$var$cor[,1:3],3))


```

```{r biplot_UNLu, echo=FALSE, warning=FALSE}
#Biplot
sit<-c(rep("A", 3), rep("P", 3), rep("R", 3))
fviz_pca_biplot(unlu_pcaFQB, axes = c(1,2),  col.ind=sit, label = "var")

```

```{r pcaFQ_RO,include=FALSE, warning=FALSE}

f_pca<-PCA(RO_db_full[,c(10,12:14,19)], scale.unit = TRUE, graph = FALSE)

print(summary(f_pca))

#autovalores
#print(f_pca$eig)
print(f_pca$eig[1:4, c(1,3)])
#correlaciones
print(round(f_pca$var$cor[,1:4],3))

```

```{r biplot_RO, echo=FALSE, warning=FALSE}
#Biplot
sit<-RO_db_full$system
fviz_pca_biplot(f_pca, axes = c(1,2),  col.ind=sit, label = "var")
#fviz_pca_biplot(f_pca, axes = c(1,3),  col.ind=sit, label = "var")
#fviz_pca_biplot(f_pca, axes = c(2,3),  col.ind=sit, label = "var")

```

```{r mat_D_unlu,include=FALSE, warning=FALSE}

ab_bulk <- read.csv("database/ab_bulk.txt", sep="")
ab_bulk[ab_bulk$sitio == "L", "sitio"] <- "A"
###########
#Llevando abundancias a densidad

#microfauna (se contaron los nemátodos de 4 sacabocados)
sup.bocado.micro <- (1/(pi*2.5^2/10000))*4
#mesofauna (se contaron y extrajeron de 3 frasquitos homojeneizados del monolito)
sup.bocado.meso <- (1/(pi*2.5^2/10000))*3
#macrofauna (superficie estandar 25 x 25)
sup.monolito <- 1/(0.25*0.25)

unlu_full<-ab_bulk%>%
  mutate(nombre=paste(sitio,replica))%>%
           mutate(
             D=floor(case_when(
  class=="macrofauna"~sup.monolito*abundance,
  class=="mesofauna"~sup.bocado.meso*abundance,
  class=="microfauna"~sup.bocado.micro*abundance)
  )
  )

####################
#Matriz comunidad

unlu_ab<-unlu_full[,c("nombre","sitio","replica","taxon","D","abundance")] %>% 
  pivot_wider(names_from = taxon,
              values_from = c(D,abundance),
              values_fill = 0,
              values_fn = sum)%>%
  distinct(nombre,.keep_all=TRUE)


##############
# variables microbiológicas adjuntas a la matriz de datos
unlu_merg<-unlu_ab
#agrego respiración en CO2/h/g
unlu_merg$resp.b<-c(0.066236559139785,0.0851612903225806,0.0946236559139785,
                    0.131588785046729,0.14803738317757,0.14803738317757,
                    0.188187372708758,0.15234215885947,0.170264765784114)
#agrego relación Hongo-Bacterias
unlu_merg$ratio.hb<-c(3.25, 14/3, 5/6, #agrícola
                       1.375, 11/6, 7/6,#pastizal
                       2.42857142857143, 11/6, 3.5) #reserva


#Valores expresados en microgramos de C-biomasa/g suelo

unlu_merg$ug_biom_x_g<-c(1.80305376344086, 2.14417204301075, 1.70559139784947,
3.78435845213849, 3.50745417515275, 3.87665987780041, 2.62601869158878,
3.4731214953271, 2.37188785046729)

# con la idea de tener la cantidad de hongos y bacterias
# densidad aparente 1,27 g/cm3 (sacado del promedio pastura, agricola, reserva, tesina
#Veronica)
# suelo a 5 cm en un m2 son 50k cm3 aprox 0.5m3, esto es, 73500 g en 0.5m3 suelo 


unlu_merg$bio.micro<-unlu_merg$ug_biom_x_g*63500


unlu_merg$fungi<-round(unlu_merg$bio.micro*(unlu_merg$ratio.hb/(unlu_merg$ratio.hb+1)),4)
unlu_merg$bacteria<-round((unlu_merg$bio.micro-unlu_merg$fungi),4)

#write.table(unlu_merg[,c(1,2,3,4,6,8,10,12,14,16,258:263,20:138)],"matrizunlu.txt")


```

**Diversidad alfa (α) en suelos Argiudoles: Riqueza de unidades taxonómicas**

```{r S, include=FALSE}
#S Luján####
D<-unlu_merg[,c(4:122,2)]
# son 118 taxones, siquisiera poner nombre a todos...
#colnames(ab)<-spc.colector

rownames(D)<-unlu_merg$nombre

S_unlu <- read.delim(
  "database/unlu_ab_mass_mean_web.txt"
  )

ab_unlu<-S_unlu[,c("sitio","replica","estrato","taxa","abundance")] %>% 
  pivot_wider(names_from = taxa,
              values_from = c(abundance),
              values_fill = 0,
              values_fn = sum)

Sitios<-unlu_merg$nombre
Riqueza<-specnumber(ab_unlu[,colnames(ab_unlu)!=c("sitio","replica","estrato")],groups = ab_unlu$sitio) #Riqueza[["R"]]
Riqueza_nematodos<-specnumber(ab_unlu[,colnames(ab_unlu)%in%c("nem_fitofago","nem_bacterivoro","nem_fungivoro","nem_omnivor","nem_predador")],groups = ab_unlu$sitio)
Riqueza_lombrices<-specnumber(ab_unlu[,colnames(ab_unlu)%in%c(
  "Aporrectodea caliginosa","Octolasion tyrtaeum","Glossoscolex sp.","Octalasion cyaneum",
  "Bimastos beddardi sophiae","Aporrectodea rosea","juvenil","Aporrectodea trapezoides",
  "Eukerria halophila","Microscolex phosphoreus","Bimastos parvus"
)],groups = ab_unlu$sitio)

Riqueza_sarcoptiformes<-specnumber(ab_unlu[,colnames(ab_unlu)%in%c(
  "oripodidae", "galumnidae", "eupthiracaroidea", "limnozetidae","macropilina","eremobelbidae",
  "eupthiracaroidea","epilhomanioidea","ceratozetoidea","astigmata","oribatulidae","scheloribatidae",
  "oppioidea","astigmata"
)],groups = ab_unlu$sitio)
Riqueza_mesostigmata<-specnumber(ab_unlu[,colnames(ab_unlu)%in%c(
 "ichtyostomatogasteridae","veigaioidea","ologamasidae","ameroseidae","mesostigmata","uropodoidea",
 "parasitidae","dermanisoidea", "laelapidae","eviphididae","arctacaridae","rhodacarioidea"
)],groups = ab_unlu$sitio)
Riqueza_prostigmata<-specnumber(ab_unlu[,colnames(ab_unlu)%in%c(
 "tarsonemidae","trombidiidae","cunaxide","anystidae","rhagidiidae","penthalidae","bdelloidea","tydeioidea",
 "teneriffidae","alycidae","eupodoidea"
)],groups = ab_unlu$sitio)
Riqueza_collembola<-specnumber(ab_unlu[,colnames(ab_unlu)%in%c(
 "entomobridae","isotomidae","symphypleona","onichiuridae"
)],groups = ab_unlu$sitio)
Riqueza_otra_mesofauna<-specnumber(ab_unlu[,colnames(ab_unlu)%in%c(
 "tardigrado","diplura","symphyla","enchytraeida"
)],groups = ab_unlu$sitio)
Riqueza_macrofauna<-specnumber(ab_unlu[,colnames(ab_unlu)%in%c(
 "larva_scarabidae","lycosidae","grillopalpidae","cicadidae","oniscidea","gasteropoda",
 "diplopoda","larva_carabidae","tenebrionidae","ortoptero","larva_sciaridae","anthribidae","hemiptero",
 "geophylomorpha","linyphiidae","carabidae","trogossitidae","larva_diptera","blattodea","coccinelidae",
 "larva_curculionidae","pupa_diptera","larva_coleoptero","larva_elateridae","larva_tenebrionidae",
 "staphiliniidae","nematomorpha","elateriforme","ptilidae","cryptophagidae","formicidae",
 "embrioptera","pseudoscorpionida","aphidoidea","terebrantia","thysanoptera","coleoptera_suctor"
)],groups = ab_unlu$sitio)

S_UNLu<-data.frame(siti= c("R", "P", "A"),
                   S=c(Riqueza[["R"]],Riqueza[["P"]],Riqueza[["L"]]),
                   S_lombrices=c(Riqueza_lombrices[["R"]],
                         Riqueza_lombrices[["P"]],Riqueza_lombrices[["L"]]),
                   S_collembola=c(Riqueza_collembola[["R"]],
                                  Riqueza_collembola[["P"]],Riqueza_collembola[["L"]]),
           S_sarcoptiformes=c(Riqueza_sarcoptiformes[["R"]],
                              Riqueza_sarcoptiformes[["P"]],Riqueza_sarcoptiformes[["L"]]),
           S_mesostigmata=c(Riqueza_mesostigmata[["R"]],
                            Riqueza_mesostigmata[["P"]],Riqueza_mesostigmata[["L"]]),
           S_prostigmata=c(Riqueza_prostigmata[["R"]],
                           Riqueza_prostigmata[["P"]],Riqueza_prostigmata[["L"]]),
           S_otra_mesofauna=c(Riqueza_otra_mesofauna[["R"]],
                              Riqueza_otra_mesofauna[["P"]],Riqueza_otra_mesofauna[["L"]]),
           S_macrofauna=c(Riqueza_macrofauna[["R"]],
                          Riqueza_macrofauna[["P"]],Riqueza_macrofauna[["L"]]),
           row.names = NULL)

#S Chyvilcoy####
#Lista de especie agrupadas según el colector
#De los datos brutos de RO
#Arrastrado a partir de los agrupamientos y pivoteo en ancho
#Nombres tomados de la columnas de abun_RO y "reformateados"
spc.colector<-c("Apo_cal","Apo_tra", "Mic_dub",
                "lom_juv","isotomidae",  "epilohmannioidea",
                "euphthiracaroidea","oripodoidea","oppioidea",
                "onychiuridae","Apo_ros",
                "parasitoidea","ceratozetoidea",
                "brachychthonioidea","crotonioidea","hypogastruridae",
                "eupodoidea","veigaioidea",
                "entomobroidea","rhodacaroidea",
                "galumnioidea","symphypleona",
               "octala","bdelloidea",
                "dermanyssoidea","trombidioidea",
                "octacy","acaroidea",
                "tydeoidea","uropodoidea","mesostigmata",
                "euker","oribatida","Mic_pho")

ab<-RO_db_full[,c(23:56,2,3)]
colnames(ab)<-c(spc.colector,"system","site")

Riq<-specnumber(ab[,-c(35,36)],groups=ab$system)

Riq_lombrices<-specnumber(ab[,c("Apo_cal","Apo_tra", "Mic_dub",
                "lom_juv","Apo_ros","octala","octacy","euker","Mic_pho")],groups=ab$system)

Riq_sarcoptiformes<-specnumber(ab[,c("epilohmannioidea",
                "euphthiracaroidea","oripodoidea","oppioidea",
               "ceratozetoidea", "brachychthonioidea","crotonioidea",
                "galumnioidea","acaroidea",
                "oribatida")],groups=ab$system)
Riq_prostigmata<-specnumber(ab[,c("eupodoidea","bdelloidea",
                                      "trombidioidea","tydeoidea")],groups=ab$system)

Riq_mesostigmata<-specnumber(ab[,c("parasitoidea","veigaioidea",
                "rhodacaroidea","dermanyssoidea","uropodoidea",
                "mesostigmata")],groups=ab$system)

Riq_collembola<-specnumber(ab[,c("isotomidae", "onychiuridae","hypogastruridae",
                "entomobroidea","symphypleona")],groups=ab$system)


#Sitios.r<-levels(as.factor(ab$system))
#Sitios.r <- factor(Sitios.r, levels = c("N", "G", "A"))



S_RO<-data.frame(siti=c("N", "G", "A"),
                 S=c(Riq[["N"]],Riq[["G"]],Riq[["A"]]),
                  S_lombrices=c(Riq_lombrices[["N"]],
                                Riq_lombrices[["G"]],Riq_lombrices[["A"]]),
                 S_collembola=c(Riq_collembola[["N"]],
                                Riq_collembola[["G"]],Riq_collembola[["A"]]),
                 S_sarcoptiformes=c(Riq_sarcoptiformes[["N"]],
                                    Riq_sarcoptiformes[["G"]],Riq_sarcoptiformes[["A"]]),
                 S_mesostigmata=c(Riq_mesostigmata[["N"]],
                                  Riq_mesostigmata[["G"]],Riq_mesostigmata[["A"]]),
                 S_prostigmata=c(Riq_prostigmata[["N"]],
                                 Riq_prostigmata[["G"]],Riq_prostigmata[["A"]]),
                 S_otra_mesofauna=c(rep("-",times=3)),
                 S_macrofauna=c(rep("-",times=3)),
                 row.names = NULL)
```


```{r Riqueza, echo=FALSE, warning=FALSE}

S<-rbind(S_UNLu,S_RO)
colnames(S)<-c("Sitios", "S", "Lombrices", "Colémbolos", "Sarcoptiformes", "Mesostigmatas", "Prostigmatas",
               "Mesofauna, otra", "Macrofauna")
(S)
```



```{r H_general_UNLu_RO, include=FALSE}
#Shanon general unlu####
#Matriz de densidades de UNLu
H<-vegan::diversity(D[,-120], index="shannon")
diversidad<-round(H,3)
Muestras<-Sitios
g_H<-data.frame(Muestras,diversidad,row.names = NULL)
g_H$sitio<-substr(g_H$Muestras,1,1)
g_H$replica<-substr(g_H$Muestras,3,3)
#data frame global de unlu
g_H.sum<-data.frame(
  Sitio=c("R","P","A"),
  
  Promedio=c(paste(sep=" ",round(mean(g_H[g_H$sitio=="R","diversidad"]),2),
      "±",
      round(sd(g_H[g_H$sitio=="R","diversidad"]),2)),
      paste(sep=" ",round(mean(g_H[g_H$sitio=="P","diversidad"]),2),
      "±",
      round(sd(g_H[g_H$sitio=="P","diversidad"]),2)),
      paste(sep=" ",round(mean(g_H[g_H$sitio=="A","diversidad"]),2),
      "±",
      round(sd(g_H[g_H$sitio=="A","diversidad"]),2))),
  Mediana=c(
             round(median(g_H[g_H$sitio=="A","diversidad"]),2),
             round(median(g_H[g_H$sitio=="P","diversidad"]),2),
             round(median(g_H[g_H$sitio=="R","diversidad"]),2)
                         )
  ,row.names = NULL
  )
#test kw unlu total
kruskal.test(diversidad ~ sitio, data = g_H)
#Shanon general ro####
# Diversidad Total Rosana se trabaja con densidad

mtxRO_D<-RO_db_full[,c(20:22,57:90)]
mtxRO_D$nombre<-paste(mtxRO_D$system.x,mtxRO_D$replica)

H_RO.D<-as.matrix(mtxRO_D[,-c(1:3,38)])
row.names(H_RO.D)<-mtxRO_D$nombre

H_RO<-vegan::diversity(H_RO.D, index="shannon")

#matriz de diversidad
RO_div<-mtxRO_D[,c(1:3,38)]

RO_div$diversidad<-H_RO
names(RO_div)<-c("replica","sitio","n_sit","nombre","diversidad")
#dataframe total H
g_H.ro<-data.frame(Sitio=c("N","G","A"),
                 Promedio=c(paste(sep=" ",round(mean(as.matrix(RO_div[RO_div$sitio=="N","diversidad"])),2),
      "±",
      round(sd(as.matrix(RO_div[RO_div$sitio=="N","diversidad"])),2)),
      paste(sep=" ",round(mean(as.matrix(RO_div[RO_div$sitio=="G","diversidad"])),2),
      "±",
      round(sd(as.matrix(RO_div[RO_div$sitio=="G","diversidad"])),2)),
      paste(sep=" ",round(mean(as.matrix(RO_div[RO_div$sitio=="A","diversidad"])),2),
      "±",
      round(sd(as.matrix(RO_div[RO_div$sitio=="A","diversidad"])),2))),
                 Mediana=c(round(median(as.matrix(RO_div[RO_div$sitio=="N","diversidad"])),2),
                        round(median(as.matrix(RO_div[RO_div$sitio=="G","diversidad"])),2),
                        round(median(as.matrix(RO_div[RO_div$sitio=="A","diversidad"])),2)
                        ),
                row.names = NULL)
#prueba kw para total
kruskal.test(diversidad ~ sitio, data = RO_div)

RO_div1<-RO_div[,c("sitio","replica","diversidad")]

g_H1<-g_H[,c("sitio","replica","diversidad")]
g_H1[g_H1$sitio == "A", "sitio"] <- "L"
#prueba kw entre todos los sitios en conjunto
hT<-rbind(g_H1,RO_div1)

kruskal.test(diversidad ~ sitio, data = hT)

pairwise.wilcox.test(hT$diversidad, hT$sitio,data=hT,
                     p.adjust.method = "BH",exact=FALSE)

#Shanon mesofauna unlu####
#carga mesofauna unlu
mesoH <- read.delim("database/mesofauna_diversityH.txt")

#reasignar nombre a agrícola

mesoH[mesoH$sitio == "L", "sitio"] <- "A"

mesoH$hab[mesoH$estrato %in% c("fragmentado","hoja","humus")] <- "H"
mesoH$hab[mesoH$estrato %in% c("10")] <- "10"
#
#Matriz comunidad

mesoH$nombre<-paste(mesoH$sitio,mesoH$replica,mesoH$hab)

meso_abH<-mesoH[,c("nombre","sitio","replica","estrato","hab","taxon","conteo")] %>% 
  pivot_wider(names_from = taxon,
              values_from = conteo,
              values_fill = 0,
              values_fn = sum)

H_meso_unlu<-as.matrix(meso_abH[,-c(1:5)])
row.names(H_meso_unlu)<-meso_abH$nombre

H_meso_unlu<-vegan::diversity(H_meso_unlu, index="shannon")
#matriz de diversidad
mesoabH<-meso_abH[,1:5]

mesoabH$diversidad<-H_meso_unlu

#meso global unlu
H_unlu_meso<-data.frame(habitats=c("R","P","A"),
                 mean=c(paste(sep=" ",round(mean(as.matrix(mesoabH[mesoabH$sitio=="R", "diversidad"])),2),
                        "±",
                        round(sd(as.matrix(mesoabH[mesoabH$sitio=="R","diversidad"])),2)),
                        paste(sep=" ",round(mean(as.matrix(mesoabH[mesoabH$sitio=="P","diversidad"])),2),
                        "±",
                        round(sd(as.matrix(mesoabH[mesoabH$sitio=="P","diversidad"])),2)),
                        paste(sep=" ",round(mean(as.matrix(mesoabH[mesoabH$sitio=="A","diversidad"])),2),
                        "±",
                        round(sd(as.matrix(mesoabH[mesoabH$sitio=="A","diversidad"])),2))),
                        
                        mediana=c(
                   round(median(as.matrix(mesoabH[mesoabH$sitio=="R","diversidad"])),2),
                   round(median(as.matrix(mesoabH[mesoabH$sitio=="P","diversidad"])),2),
                   round(median(as.matrix(mesoabH[mesoabH$sitio=="A","diversidad"])),2)),row.names = NULL)

#meso estrato unlu
meso_H_UNLu<-data.frame(habitats=c("R H","P H","A H","R 10","P 10","A 10"),
                 mean=c(paste(sep=" ",round(mean(as.matrix(mesoabH[mesoabH$sitio=="R" & mesoabH$hab=="H","diversidad"])),2),
                        "±",
                        round(sd(as.matrix(mesoabH[mesoabH$sitio=="R" & mesoabH$hab=="H","diversidad"])),2)),
                        paste(sep=" ",round(mean(as.matrix(mesoabH[mesoabH$sitio=="P" & mesoabH$hab=="H","diversidad"])),2),
                        "±",
                        round(sd(as.matrix(mesoabH[mesoabH$sitio=="P" & mesoabH$hab=="H","diversidad"])),2)),
                        paste(sep=" ",round(mean(as.matrix(mesoabH[mesoabH$sitio=="A" & mesoabH$hab=="H","diversidad"])),2),
                        "±",
                        round(sd(as.matrix(mesoabH[mesoabH$sitio=="A" & mesoabH$hab=="H","diversidad"])),2)),
                        
                        paste(sep=" ",round(mean(as.matrix(mesoabH[mesoabH$sitio=="R" & mesoabH$hab=="10","diversidad"])),2),
                        "±",
                        round(sd(as.matrix(mesoabH[mesoabH$sitio=="R" & mesoabH$hab=="10","diversidad"])),2)),
                        
                        paste(sep=" ",round(mean(as.matrix(mesoabH[mesoabH$sitio=="P" & mesoabH$hab=="10","diversidad"])),2),
                        "±",
                        round(sd(as.matrix(mesoabH[mesoabH$sitio=="P" & mesoabH$hab=="10","diversidad"])),2)),
                        
                 paste(sep=" ",round(mean(as.matrix(mesoabH[mesoabH$sitio=="A" & mesoabH$hab=="10","diversidad"])),2),
                        "±",
                        round(sd(as.matrix(mesoabH[mesoabH$sitio=="A" & mesoabH$hab=="10","diversidad"])),2))),
                        
                        mediana=c(
                   median(as.matrix(mesoabH[mesoabH$sitio=="R" & mesoabH$hab=="H","diversidad"])),
                   median(as.matrix(mesoabH[mesoabH$sitio=="P" & mesoabH$hab=="H","diversidad"])),
                   median(as.matrix(mesoabH[mesoabH$sitio=="A" & mesoabH$hab=="H","diversidad"])),
                   median(as.matrix(mesoabH[mesoabH$sitio=="R" & mesoabH$hab=="10","diversidad"])),
                   median(as.matrix(mesoabH[mesoabH$sitio=="P" & mesoabH$hab=="10","diversidad"])),
                   median(as.matrix(mesoabH[mesoabH$sitio=="A" & mesoabH$hab=="10","diversidad"]))),row.names = NULL)
                

kruskal.test(diversidad ~ sitio, data = mesoabH, subset=mesoabH$hab=="H")
kruskal.test(diversidad ~ sitio, data = mesoabH, subset=mesoabH$hab=="10")


#shanon meso RO####

spc.colector<-c("Apo_cal","Apo_tra", "Mic_dub",
                "lom_juv","isotomidae",  "epilohmannioidea",
                "euphthiracaroidea","oripodoidea","oppioidea",
                "onychiuridae","Apo_ros",
                "parasitoidea","ceratozetoidea",
                "brachychthonioidea","crotonioidea","hypogastruridae",
                "eupodoidea","veigaioidea",
                "entomobroidea","rhodacaroidea",
                "galumnioidea","symphypleona",
               "octala","bdelloidea",
                "dermanyssoidea","trombidioidea",
                "octacy","acaroidea",
                "tydeoidea","uropodoidea","mesostigmata",
                "euker","oribatida","Mic_pho")

mtxRO_D<-RO_db_full[,c(20:22,57:90)]

mtxRO_D$nombre<-paste(mtxRO_D$system.y,mtxRO_D$replica)

lomb<-c("D_Apo_cal","D_Apo_tra", "D_Mic_dub","D_lom_juv","D_Apo_ros","D_octala","D_octacy","D_euker","D_Mic_pho")
l.par<-mtxRO_D[,!colnames(mtxRO_D)%in%lomb]
#mtxRO_D[,!colnames(mtxRO_D)%in%"D_Apo_tra"]
#H_RO.D.meso<-as.matrix(mtxRO_D[,-c(1:3,38,4:7,14,26,30,35,37)])
H_RO.D.meso<-as.matrix(l.par[,-c(1:3,29)])
row.names(H_RO.D.meso)<-mtxRO_D$nombre

H_RO.D.meso[is.na(H_RO.D.meso)]<-0

H_RO.meso<-vegan::diversity(H_RO.D.meso, index="shannon")

#matriz de diversidad
RO_div.meso<-mtxRO_D[,c(1:3,38)]

RO_div.meso$diversidad<-H_RO.meso
names(RO_div.meso)<-c("replica","sitio","n_sit","nombre","diversidad")

#data frame H Ro
g_H.ro.meso<-data.frame(Sitio=c("N","G","A"),
                 Promedio=c(
                    paste(sep=" ",round(mean(mean(as.matrix(RO_div.meso[RO_div.meso$sitio=="N","diversidad"]))),2),
                        "±",
                        round(sd(as.matrix(RO_div.meso[RO_div.meso$sitio=="N","diversidad"])),2)),
                    paste(sep=" ",round(mean(mean(as.matrix(RO_div.meso[RO_div.meso$sitio=="G","diversidad"]))),2),
                        "±",
                        round(sd(as.matrix(RO_div.meso[RO_div.meso$sitio=="G","diversidad"])),2)),
                    paste(sep=" ",round(mean(mean(as.matrix(RO_div.meso[RO_div.meso$sitio=="A","diversidad"]))),2),
                        "±",
                        round(sd(as.matrix(RO_div.meso[RO_div.meso$sitio=="A","diversidad"])),2))
                 ),
                 Mediana=c(round(median(as.matrix(RO_div.meso[RO_div.meso$sitio=="N","diversidad"])),2),
                        round(median(as.matrix(RO_div.meso[RO_div.meso$sitio=="G","diversidad"])),2),
                        round(median(as.matrix(RO_div.meso[RO_div.meso$sitio=="A","diversidad"])),2)
                        ),
                row.names = NULL)

kruskal.test(diversidad ~ sitio, data = RO_div.meso)


#shanon macro RO####
#lombrices_ro
mtxRO_D<-RO_db_full[,c(20:22,57:90)]
mtxRO_D$nombre<-paste(mtxRO_D$system.y,mtxRO_D$replica)
H_RO.D.lom<-as.matrix(mtxRO_D[,c(4:7,14,26,30,35,37)])
row.names(H_RO.D.lom)<-mtxRO_D$nombre

H_RO.lom<-vegan::diversity(H_RO.D.lom, index="shannon")

#matriz de diversidad
RO_div.meso.lom<-mtxRO_D[,c(1:3,38)]

RO_div.meso.lom$diversidad<-H_RO.lom
names(RO_div.meso.lom)<-c("replica","sitio","n_sit","nombre","diversidad")
#data frame lombrices ro
g_H.ro.lomb<-data.frame(Sitio=c("N","G","A"),
                 Promedio=c(
                   paste(sep=" ",round(mean(as.matrix(RO_div.meso.lom[RO_div.meso.lom$sitio=="N","diversidad"])),2),
                        "±",
                        round(sd(as.matrix(RO_div.meso.lom[RO_div.meso.lom$sitio=="N","diversidad"])),2)),
                   paste(sep=" ",round(mean(as.matrix(RO_div.meso.lom[RO_div.meso.lom$sitio=="G","diversidad"])),2),
                        "±",
                        round(sd(as.matrix(RO_div.meso.lom[RO_div.meso.lom$sitio=="G","diversidad"])),2)),
                   paste(sep=" ",round(mean(as.matrix(RO_div.meso.lom[RO_div.meso.lom$sitio=="A","diversidad"])),2),
                        "±",
                        round(sd(as.matrix(RO_div.meso.lom[RO_div.meso.lom$sitio=="A","diversidad"])),2))
                 ),
                 Mediana=c(round(median(as.matrix(RO_div.meso.lom[RO_div.meso.lom$sitio=="N","diversidad"])),2),
                        round(median(as.matrix(RO_div.meso.lom[RO_div.meso.lom$sitio=="G","diversidad"])),2),
                        round(median(as.matrix(RO_div.meso.lom[RO_div.meso.lom$sitio=="A","diversidad"])),2)
                        ),
                row.names = NULL)

kruskal.test(diversidad ~ sitio, data = RO_div.meso.lom)

#H' macro lujan#######
#macro luján
macroH <- read.delim("database/macrofauna_diversityH.txt")

#reasignar nombre a agrícola

macroH[macroH$sitio == "L", "sitio"] <- "A"

#
#Matriz comunidad

macroH$nombre<-paste(macroH$sitio,macroH$replica,macroH$estrato)

macro_abH<-macroH[,c("nombre","sitio","replica","estrato","taxon","abundance")] %>% 
  pivot_wider(names_from = taxon,
              values_from = abundance,
              values_fill = 0,
              values_fn = sum)%>%
  distinct(nombre,.keep_all=TRUE)

#lombrices = ,20:23,30,44:46,49
H_macro_unlu<-as.matrix(macro_abH[,-c(1:4,15,20:23,30,44:46,49)]) #toda la macro sin lombrices
row.names(H_macro_unlu)<-macro_abH$nombre
#selección solo lomb unlu
H_lom_unlu<-as.matrix(macro_abH[,c(20:23,30,44:46,49)])
row.names(H_lom_unlu)<-macro_abH$nombre
#calculo shanon macro
H_macro_unlu<-vegan::diversity(H_macro_unlu, index="shannon")
#calculo shanon lomb
H_lom_unlu<-vegan::diversity(H_lom_unlu, index="shannon")

#matriz de diversidad macro total
macroabH<-macro_abH[,1:4]
macroabH$diversidad<-H_macro_unlu

#matrizz diversidad unlu lomb 
macroabH_l<-macro_abH[,1:4]
macroabH_l$diversidad<-H_lom_unlu

#tabla diversidad macro por estrato
macro_H_U<-data.frame(habitats=levels(as.factor(paste(macroabH$sitio,macroabH$estrato))),
                 mean=c(
                   mean(as.matrix(macroabH[macroabH$sitio=="A" & macroabH$estrato=="10","diversidad"])),
                   mean(as.matrix(macroabH[macroabH$sitio=="A" & macroabH$estrato=="20","diversidad"])),
                   mean(as.matrix(macroabH[macroabH$sitio=="A" & macroabH$estrato=="H","diversidad"])),
                   mean(as.matrix(macroabH[macroabH$sitio=="P" & macroabH$estrato=="10","diversidad"])),
                   mean(as.matrix(macroabH[macroabH$sitio=="P" & macroabH$estrato=="20","diversidad"])),
                   mean(as.matrix(macroabH[macroabH$sitio=="P" & macroabH$estrato=="H","diversidad"])),
                   mean(as.matrix(macroabH[macroabH$sitio=="R" & macroabH$estrato=="10","diversidad"])),
                   mean(as.matrix(macroabH[macroabH$sitio=="R" & macroabH$estrato=="20","diversidad"])),
                   mean(as.matrix(macroabH[macroabH$sitio=="R" & macroabH$estrato=="H","diversidad"]))),
                 desvio_std=c(
                   sd(as.matrix(macroabH[macroabH$sitio=="A" & macroabH$estrato=="10","diversidad"])),
                   sd(as.matrix(macroabH[macroabH$sitio=="A" & macroabH$estrato=="20","diversidad"])),
                   sd(as.matrix(macroabH[macroabH$sitio=="A" & macroabH$estrato=="H","diversidad"])),
                   sd(as.matrix(macroabH[macroabH$sitio=="P" & macroabH$estrato=="10","diversidad"])),
                   sd(as.matrix(macroabH[macroabH$sitio=="P" & macroabH$estrato=="20","diversidad"])),
                   sd(as.matrix(macroabH[macroabH$sitio=="P" & macroabH$estrato=="H","diversidad"])),
                   sd(as.matrix(macroabH[macroabH$sitio=="R" & macroabH$estrato=="10","diversidad"])),
                   sd(as.matrix(macroabH[macroabH$sitio=="R" & macroabH$estrato=="20","diversidad"])),
                   sd(as.matrix(macroabH[macroabH$sitio=="R" & macroabH$estrato=="H","diversidad"]))),
                 mediana=c(
                   median(as.matrix(macroabH[macroabH$sitio=="A" & macroabH$estrato=="10","diversidad"])),
                   median(as.matrix(macroabH[macroabH$sitio=="A" & macroabH$estrato=="20","diversidad"])),
                   median(as.matrix(macroabH[macroabH$sitio=="A" & macroabH$estrato=="H","diversidad"])),
                   median(as.matrix(macroabH[macroabH$sitio=="P" & macroabH$estrato=="10","diversidad"])),
                   median(as.matrix(macroabH[macroabH$sitio=="P" & macroabH$estrato=="20","diversidad"])),
                   median(as.matrix(macroabH[macroabH$sitio=="P" & macroabH$estrato=="H","diversidad"])),
                   median(as.matrix(macroabH[macroabH$sitio=="R" & macroabH$estrato=="10","diversidad"])),
                   median(as.matrix(macroabH[macroabH$sitio=="R" & macroabH$estrato=="20","diversidad"])),
                   median(as.matrix(macroabH[macroabH$sitio=="R" & macroabH$estrato=="H","diversidad"]))),
                row.names = NULL)

#macro por sitio sin estrato
macro_H_U_t<-data.frame(Sitios=levels(as.factor(macroabH$sitio)),
                 Promedio=c(
                   paste(sep=" ",round(mean(as.matrix(macroabH[macroabH$sitio=="R","diversidad"])),2),
                        "±",
                        round(sd(as.matrix(macroabH[macroabH$sitio=="R","diversidad"])),2)),
                   paste(sep=" ",round(mean(as.matrix(macroabH[macroabH$sitio=="P","diversidad"])),2),
                        "±",
                        round(sd(as.matrix(macroabH[macroabH$sitio=="P","diversidad"])),2)),
                   paste(sep=" ",round(mean(as.matrix(macroabH[macroabH$sitio=="A","diversidad"])),2),
                        "±",
                        round(sd(as.matrix(macroabH[macroabH$sitio=="A","diversidad"])),2))
                 ),
                 Mediana=c(
                   round(median(as.matrix(macroabH[macroabH$sitio=="R","diversidad"])),2),
                   round(median(as.matrix(macroabH[macroabH$sitio=="P","diversidad"])),2),
                   round(median(as.matrix(macroabH[macroabH$sitio=="A","diversidad"])),2)),
                row.names = NULL)


kruskal.test(diversidad ~ sitio, data = macroabH, subset=macroabH$estrato=="H")
kruskal.test(diversidad ~ sitio, data = macroabH, subset=macroabH$estrato=="10")
kruskal.test(diversidad ~ sitio, data = macroabH, subset=macroabH$estrato=="20")

kruskal.test(diversidad ~ sitio, data = macroabH)

#Diversidad lombrices por estrato

kruskal.test(diversidad ~ sitio, data = macroabH_l, subset=macroabH_l$estrato=="H")
kruskal.test(diversidad ~ sitio, data = macroabH_l, subset=macroabH_l$estrato=="10")
kruskal.test(diversidad ~ sitio, data = macroabH_l, subset=macroabH_l$estrato=="20")

kruskal.test(diversidad ~ sitio, data = macroabH_l)

#data frame lombrices estrato unlu
lomb_H_U<-data.frame(sitio=levels(as.factor(paste(macroabH_l$sitio,macroabH_l$estrato))),
                 mean=c(
                   mean(as.matrix(macroabH_l[macroabH_l$sitio=="A" & macroabH_l$estrato=="10","diversidad"])),
                   mean(as.matrix(macroabH_l[macroabH_l$sitio=="A" & macroabH_l$estrato=="20","diversidad"])),
                   mean(as.matrix(macroabH_l[macroabH_l$sitio=="A" & macroabH_l$estrato=="H","diversidad"])),
                   mean(as.matrix(macroabH_l[macroabH_l$sitio=="P" & macroabH_l$estrato=="10","diversidad"])),
                   mean(as.matrix(macroabH_l[macroabH_l$sitio=="P" & macroabH_l$estrato=="20","diversidad"])),
                   mean(as.matrix(macroabH_l[macroabH_l$sitio=="P" & macroabH_l$estrato=="H","diversidad"])),
                   mean(as.matrix(macroabH_l[macroabH_l$sitio=="R" & macroabH_l$estrato=="10","diversidad"])),
                   mean(as.matrix(macroabH_l[macroabH_l$sitio=="R" & macroabH_l$estrato=="20","diversidad"])),
                   mean(as.matrix(macroabH_l[macroabH_l$sitio=="R" & macroabH_l$estrato=="H","diversidad"]))),
                 desvio_std=c(
                   sd(as.matrix(macroabH_l[macroabH_l$sitio=="A" & macroabH_l$estrato=="10","diversidad"])),
                   sd(as.matrix(macroabH_l[macroabH_l$sitio=="A" & macroabH_l$estrato=="20","diversidad"])),
                   sd(as.matrix(macroabH_l[macroabH_l$sitio=="A" & macroabH_l$estrato=="H","diversidad"])),
                   sd(as.matrix(macroabH_l[macroabH_l$sitio=="P" & macroabH_l$estrato=="10","diversidad"])),
                   sd(as.matrix(macroabH_l[macroabH_l$sitio=="P" & macroabH_l$estrato=="20","diversidad"])),
                   sd(as.matrix(macroabH_l[macroabH_l$sitio=="P" & macroabH_l$estrato=="H","diversidad"])),
                   sd(as.matrix(macroabH_l[macroabH_l$sitio=="R" & macroabH_l$estrato=="10","diversidad"])),
                   sd(as.matrix(macroabH_l[macroabH_l$sitio=="R" & macroabH_l$estrato=="20","diversidad"])),
                   sd(as.matrix(macroabH_l[macroabH_l$sitio=="R" & macroabH_l$estrato=="H","diversidad"]))),
                 mediana=c(
                   median(as.matrix(macroabH_l[macroabH_l$sitio=="A" & macroabH_l$estrato=="10","diversidad"])),
                   median(as.matrix(macroabH_l[macroabH_l$sitio=="A" & macroabH_l$estrato=="20","diversidad"])),
                   median(as.matrix(macroabH_l[macroabH_l$sitio=="A" & macroabH_l$estrato=="H","diversidad"])),
                   median(as.matrix(macroabH_l[macroabH_l$sitio=="P" & macroabH_l$estrato=="10","diversidad"])),
                   median(as.matrix(macroabH_l[macroabH_l$sitio=="P" & macroabH_l$estrato=="20","diversidad"])),
                   median(as.matrix(macroabH_l[macroabH_l$sitio=="P" & macroabH_l$estrato=="H","diversidad"])),
                   median(as.matrix(macroabH_l[macroabH_l$sitio=="R" & macroabH_l$estrato=="10","diversidad"])),
                   median(as.matrix(macroabH_l[macroabH_l$sitio=="R" & macroabH_l$estrato=="20","diversidad"])),
                   median(as.matrix(macroabH_l[macroabH_l$sitio=="R" & macroabH_l$estrato=="H","diversidad"]))),
                row.names = NULL)

#data frame lombrices general unlu
lomb_H_U_t<-data.frame(sitio=c("R","P","A"),
                 mean=c(
                   paste(sep=" ",round(mean(as.matrix(macroabH_l[macroabH_l$sitio=="R","diversidad"])),2),
                        "±",
                        round(sd(as.matrix(macroabH_l[macroabH_l$sitio=="R","diversidad"])),2)),
                   paste(sep=" ",round(mean(as.matrix(macroabH_l[macroabH_l$sitio=="P","diversidad"])),2),
                        "±",
                        round(sd(as.matrix(macroabH_l[macroabH_l$sitio=="P","diversidad"])),2)),
                   paste(sep=" ",round(mean(as.matrix(macroabH_l[macroabH_l$sitio=="A","diversidad"])),2)
                   ,"±", round(sd(as.matrix(macroabH_l[macroabH_l$sitio=="A","diversidad"])),2))),
                 mediana=c(
                   round(median(as.matrix(macroabH_l[macroabH_l$sitio=="R","diversidad"])),2),
                   round(median(as.matrix(macroabH_l[macroabH_l$sitio=="P","diversidad"])),2),
                   round(median(as.matrix(macroabH_l[macroabH_l$sitio=="A","diversidad"])),2)),
                row.names = NULL)

#nematodos lujan####
microH <- read.delim("database/nematofauna_diversityH.txt")

microH$sitio<-substr(microH$nombre,3,3)
microH$replica<-substr(microH$nombre,4,4)

microH[microH$sitio == "L", "sitio"] <- "A"

micro_abH<-microH[,c("nombre","sitio","replica","taxon","abundance")] %>% 
  pivot_wider(names_from = taxon,
              values_from = abundance,
              values_fill = 0,
              values_fn = sum)%>%
  distinct(nombre,.keep_all=TRUE)


H_micro_unlu<-as.matrix(micro_abH[,-c(1:3)])
row.names(H_micro_unlu)<-micro_abH$nombre

H_micro_unlu<-vegan::diversity(H_micro_unlu, index="shannon")

#matriz de diversidad
microabH<-micro_abH[,1:3]
microabH$diversidad<-H_micro_unlu

#data frame nematodos
H_nem<-data.frame(Sitios=c("R","P","A"),
                 Promedio=c(
                    paste(sep=" ",round(mean(as.matrix(microabH[microabH$sitio=="R","diversidad"])),2),
                        "±",
                        round(sd(as.matrix(microabH[microabH$sitio=="R","diversidad"])),2)),
                    paste(sep=" ",round(mean(as.matrix(microabH[microabH$sitio=="P","diversidad"])),2),
                        "±",
                        round(sd(as.matrix(microabH[microabH$sitio=="P","diversidad"])),2)),
                    paste(sep=" ",round(mean(as.matrix(microabH[microabH$sitio=="A","diversidad"])),2),
                        "±",
                        round(sd(as.matrix(microabH[microabH$sitio=="A","diversidad"])),2))
                 ),
                 Mediana=c(
                   round(median(as.matrix(microabH[microabH$sitio=="R","diversidad"])),2),
                                         round(median(as.matrix(microabH[microabH$sitio=="P","diversidad"])),2),
                        round(median(as.matrix(microabH[microabH$sitio=="A","diversidad"])),2)
                        ),
                row.names = NULL)

kruskal.test(diversidad ~ sitio, data = microabH)

#todas las pruebas de kw para sitios, no por estratos
kw_all_com<-list(kruskal.test(diversidad ~ sitio, data = g_H),kruskal.test(diversidad ~ sitio, data = RO_div),kruskal.test(diversidad ~ sitio, data = mesoabH),kruskal.test(diversidad ~ sitio, data = RO_div.meso),kruskal.test(diversidad ~ sitio, data = macroabH),kruskal.test(diversidad ~ sitio, data = RO_div.meso.lom),kruskal.test(diversidad ~ sitio, data = macroabH_l),kruskal.test(diversidad ~ sitio, data = microabH))

#unir todos los datos y crear tabla####
Hg<-rbind(g_H.sum,g_H.ro)
names(H_unlu_meso)<-c("Sitio","Promedio","Mediana")
Hme<-rbind(H_unlu_meso,g_H.ro.meso)
names(lomb_H_U_t)<-c("Sitio","Promedio","Mediana")
Hl<-rbind(lomb_H_U_t,g_H.ro.lomb)
names(macro_H_U_t)<-c("Sitio","Promedio","Mediana")
Hma<-rbind(macro_H_U_t, data_frame(Sitio=c("N","G","A"),Promedio=c("-","-","-"),
                                   Mediana=c("-","-","-")))
names(H_nem)<-c("Sitio","Promedio","Mediana")
Hne<-rbind(H_nem, data_frame(Sitio=c("N","G","A"),Promedio=c("-","-","-"),
                                   Mediana=c("-","-","-")))
H<-cbind(Hg,Hl,Hme,Hma,Hne)
H<-H[,-c(4,7,10,13)]

#paste("X̅ ± σ",";","X̂")
H<-rbind(c("","X̅ ± σ","X̂","X̅ ± σ","X̂","X̅ ± σ","X̂","X̅ ± σ","X̂","X̅ ± σ","X̂"), H)

colnames(H)<-c("Sitios","Total","  ","Lombrices","   ","Mesofauna","    ","Macrofauna","     ","Microfauna","         ")

```

```{r tabla_Shannon, echo=FALSE, warning=FALSE}
H
```

```{r anosim_unlu, include=FALSE, warning=FALSE}

tb_D_anosim<-D
row.names(tb_D_anosim)<-unlu_merg$nombre
tb_D_anosim1<-tb_D_anosim
tb_D_anosim1$sitio<-unlu_merg$sitio
tb_Duni_anosim<-decostand(tb_D_anosim1[,!colnames(tb_D_anosim1)%in%"sitio"],"log")
#col_sp<-colnames(tb_D)

D_unlu_anosim<-vegan::anosim(tb_Duni_anosim, 
              as.matrix(tb_D_anosim1[,"sitio"]), 
              permutations = 1670, 
              distance = "bray")
print("Resumen del ANOSIM para los datos de densidad log +1 transformados")
summary(D_unlu_anosim)

r_unlu_anosim<-D_unlu_anosim[["statistic"]]

#Rosana

#Densidad nro ind/m2
#Se utiliará la transformación "log" = (log x) + 1 si x > 0 o 0 si x = 0
#Especies ocasionales, no muestreados correctamente
#En total 18 especies, 

spe.no<-c(6,13,20,22,24,27,28,29,30,31,33,36,40,42,46,50,51,52)

#Listado completo de especies
D_anosim<-RO_db_full[,c(1,2,3,20,57:90)]
colnames(D_anosim)<-c("nombre","system","site","replica",spc.colector)

tb_D<-decostand(D_anosim[,-c(1:4)],"log")

Den_anosim<-vegan::anosim(tb_D, 
              as.matrix(D_anosim[,"system"]), 
              permutations = 1670, 
              distance = "bray")
print("Resumen del ANOSIM para los datos de densidad log +1 transformados")
summary(Den_anosim)
r_RO_anosim<-Den_anosim[["statistic"]]

```

```{r Beta_div, include=FALSE, warning=FALSE}

#uso matriz de abundancias UNLU
#4:122 Densidad | 123:241 abundancias
beta_u<-unlu_merg[,4:122]
row.names(beta_u)<-unlu_merg$"nombre"
#método 8 es el índice de wilson
#beta_div_u<-betadiver(beta_u, method=8)
beta_div_u<-vegdist(beta_u, method="bray")
#beta_div_u<-betadiver(beta_u, method=8)
#vegdist(beta_u, method="bray")
div.beta.unlu<-hclust(beta_div_u,method = "average")

#ROSANA
D_site<-RO_full[,c("system","site","specie","D")] %>% 
  pivot_wider(names_from = specie,
              values_from = D,
              values_fill = 0,
              values_fn = sum)%>%
  distinct(system,.keep_all=TRUE)
D_site<-as.data.frame(D_site)
D_site$replica
D_site[D_site$site=="triangulo","replica"]<-1
D_site[D_site$site=="L27","replica"]<-1
D_site[D_site$site=="molino","replica"]<-1

D_site[D_site$site=="festuca","replica"]<-2
D_site[D_site$site=="L24","replica"]<-2
D_site[D_site$site=="manga","replica"]<-2

D_site[D_site$site=="romina","replica"]<-3
D_site[D_site$site=="L25","replica"]<-3
D_site[D_site$site=="casuarina","replica"]<-3

row.names(D_site)<-paste(D_site$system,D_site$replica)

######
# Disimilitudd entre los sitios
betaBK_ro<-vegdist(D_site[,-c(1,2,55)], method="bray")
  #vegdist(D_site[,-c(1,2,55)], method="bray")
  #betadiver(D_site[,-c(1,2,55)],method=8)
  
div.beta<-hclust(betaBK_ro,method = "average") #average


#######
# Índice de Beta Diveridad
#beta<-betadiver(D_site[,-c(1,2)], method=8)
#div.beta<-hclust(beta,method = "mcquitty")
#plot(div.beta,cex=0.6,main="Agrupamiento según índice Wilson",sub="Diversidad Beta entre sitios",ylab="Índice de Wilson",xlab="")



```

```{r Beta, echo=FALSE, warning=FALSE, message=FALSE, fig.align='center'}
par(mfrow=c(1,2))
#UNLu
plot(div.beta.unlu,cex=0.6,main="Luján",
     sub="Agrupamiento jerárquico promedio",
     ylab="Índice de Bray Curtis",xlab="Disimilitud entre sistemas de uso")
#linea de corte
#abline(h = 0.29, lty = 2, col = "black")
#Rosana
plot(div.beta,cex=0.6,main="Chivilcoy y Navarro",
     sub="Agrupamiento jerárquico promedio",
     ylab="Índice de Bray Curtis",xlab="Disimilitud entre sistemas de uso")
par(mfrow=c(1,1))
```

```{r pca_tb, include=FALSE,warning=FALSE}
#hellinger
tb_D_U<-decostand(D[,!colnames(D)%in%c("sitio","D_insecta_egg","D_crisalida_insecto")],"log")
row.names(tb_D_U)<-unlu_merg$"nombre"
col_sp<-colnames(tb_D_U)

col.sp.unlu<-c("macro_herb","ing","ing","ing","ast","macro_pred","macro_fun",
               "macro_det","pros","macro_det","enchy","art","macro_omn","macro_pred",
               "macro_herb","art","macro_pred","meso","ing","macro_det","macro_herb",
               "macro_pred","no.art","macro_det","macro_herb","meso","pros","meso",
               "orib","pros","orib","art","macro_pred","macro_herb","macro_det",
               "macro_fun","macro_det","macro_det","meso","nem_bac","nem_fit",
               "nem_fung","nem_omn","nem_pre","meso","art","orib","orib","orib",
               "orib","meso","pros","pros","macro_det","pros","meso","orib","pros",
               "pros","macro_pred","ing","macro_det","macro_pred","orib","orib",
               "meso","art","meso","macro_det","macro_herb","macro_herb","macro_pred",
               "macro_parasi","macro_det","pros","tardi","macro_pred",
               "no.art","macro_pred","pros","pros","macro_herb","macro_herb","orib",
               "macro_det","ing","ing","ing","macro_det","macro_det","macro_pred",
               "ing","macro_det","orib","meso","meso","ing","ing","macro_det",
               "macro_det","meso","orib","no.art","orib","orib",
               "orib","orib","art","orib","macro_fun","macro_det","pros","meso",
               "orib","orib","macro_pred","macro_herb")
col.sp.unlu[col.sp.unlu=="ing"]<-"lom"
col.sp.unlu[col.sp.unlu=="macro_parasi"]<-"macro_pred"
col.sp.unlu[col.sp.unlu=="art"]<-"col"
col.sp.unlu[col.sp.unlu=="no.art"]<-"mesof"
#col.sp.unlu[col.sp.unlu=="tardi"]<-"mesof"
#col.sp.unlu[col.sp.unlu=="enchy"]<-"mesof"

#Matriz transpuesta
tb_U_D_pca<-PCA(t(tb_D_U), scale.unit = TRUE, graph = FALSE)
summary(tb_U_D_pca)

#tb_U_D_pca[["var"]][["cor"]][,1]
#tb_U_D_pca[["var"]][["cor"]][,2]

##corelaciones
f_pca_cor<-round(tb_U_D_pca$var$cor[,1:4],3)
#Biplot
sit<-c(rep("A", 3), rep("P", 3), rep("R", 3))

plot_PCA_unlu<-fviz_pca_biplot(tb_U_D_pca, axes = c(1,2), col.var = "black", #as.factor(sit),
                col.ind =  as.factor(col.sp.unlu),
                alpha.ind=0.2,
                alpha.var=0.4,
                label = "var",
                repel=TRUE) +
  theme(legend.position = "bottom")
  
#####
#Rosana

tb_D<-decostand(D_site[,-c(1,2,37)],"log")
sit<-c(rep("A", 3), rep("G", 3), rep("N", 3))

pch<-c(1,1,1,1,9,5,5,5,5,9,1,6,5,5,5,9,7,6,
         9,6,5,10,1,7,6,7,1,5,
           7,6,6,1,5,1)
col.sp<-pch
col.sp <- case_when(
  col.sp == 1 ~ "lom",
  col.sp == 5 ~ "ori",
  col.sp == 6 ~ "mes",
  col.sp == 7 ~ "pro",
  col.sp == 9 ~ "col", #art
  col.sp == 10 ~ "col", #no.art
  TRUE ~ as.character(col.sp)
)

#lombrices=1=lom; macro=3=macro; acaros_orib= 5=ori; ac_meso= 6=mes
#ac_prost=7=pro; artropleona=9=art; no_artropleona=10=no.art



####################
#con Densidades standarizadas por log(ab)+1

std_ab_pca<-PCA(t(tb_D), scale.unit = TRUE, graph = FALSE)

summary(std_ab_pca)
#correlaciones
std_ab_pca_cor<-round(std_ab_pca$var$cor[,1:5],3)

#fviz_pca_var(std_ab_pca, col.var=sit,repel = TRUE, label="none")

#fviz_pca_ind(std_ab_pca, col.ind=col.sp,label="none",repel = TRUE)
          
plot_PCA_ro<-fviz_pca_biplot(std_ab_pca, axes = c(1,2) , col.ind=col.sp,
                col.var = "black", alpha.var=0.6,#as.factor(sit),
                alpha.ind=0.3,
                repel = TRUE,label = "var")+
  theme(legend.position = "bottom")


```

```{r plot_pca_U, echo=FALSE, warning=FALSE,message=FALSE,fig.align='center'}
plot_PCA_unlu

```

```{r plot_pca_Ro, echo=FALSE, warning=FALSE,fig.align='center'}

plot_PCA_ro

ggsave("database/Fig3-6.png",width=8,height=8,units="in",dpi=600)
```

